// Code generated by ent, DO NOT EDIT.

package investmentlot

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the investmentlot type in the database.
	Label = "investment_lot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldHouseholdID holds the string denoting the household_id field in the database.
	FieldHouseholdID = "household_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldInvestmentID holds the string denoting the investment_id field in the database.
	FieldInvestmentID = "investment_id"
	// FieldTransactionID holds the string denoting the transaction_id field in the database.
	FieldTransactionID = "transaction_id"
	// EdgeHousehold holds the string denoting the household edge name in mutations.
	EdgeHousehold = "household"
	// EdgeInvestment holds the string denoting the investment edge name in mutations.
	EdgeInvestment = "investment"
	// EdgeTransaction holds the string denoting the transaction edge name in mutations.
	EdgeTransaction = "transaction"
	// Table holds the table name of the investmentlot in the database.
	Table = "investment_lots"
	// HouseholdTable is the table that holds the household relation/edge.
	HouseholdTable = "investment_lots"
	// HouseholdInverseTable is the table name for the Household entity.
	// It exists in this package in order to avoid circular dependency with the "household" package.
	HouseholdInverseTable = "households"
	// HouseholdColumn is the table column denoting the household relation/edge.
	HouseholdColumn = "household_id"
	// InvestmentTable is the table that holds the investment relation/edge.
	InvestmentTable = "investment_lots"
	// InvestmentInverseTable is the table name for the Investment entity.
	// It exists in this package in order to avoid circular dependency with the "investment" package.
	InvestmentInverseTable = "investments"
	// InvestmentColumn is the table column denoting the investment relation/edge.
	InvestmentColumn = "investment_id"
	// TransactionTable is the table that holds the transaction relation/edge.
	TransactionTable = "investment_lots"
	// TransactionInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionInverseTable = "transactions"
	// TransactionColumn is the table column denoting the transaction relation/edge.
	TransactionColumn = "transaction_id"
)

// Columns holds all SQL columns for investmentlot fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldHouseholdID,
	FieldAmount,
	FieldPrice,
	FieldInvestmentID,
	FieldTransactionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "beavermoney.app/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// InvestmentIDValidator is a validator for the "investment_id" field. It is called by the builders before save.
	InvestmentIDValidator func(int) error
	// TransactionIDValidator is a validator for the "transaction_id" field. It is called by the builders before save.
	TransactionIDValidator func(int) error
)

// OrderOption defines the ordering options for the InvestmentLot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByHouseholdID orders the results by the household_id field.
func ByHouseholdID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHouseholdID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByInvestmentID orders the results by the investment_id field.
func ByInvestmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvestmentID, opts...).ToFunc()
}

// ByTransactionID orders the results by the transaction_id field.
func ByTransactionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionID, opts...).ToFunc()
}

// ByHouseholdField orders the results by household field.
func ByHouseholdField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHouseholdStep(), sql.OrderByField(field, opts...))
	}
}

// ByInvestmentField orders the results by investment field.
func ByInvestmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvestmentStep(), sql.OrderByField(field, opts...))
	}
}

// ByTransactionField orders the results by transaction field.
func ByTransactionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransactionStep(), sql.OrderByField(field, opts...))
	}
}
func newHouseholdStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HouseholdInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HouseholdTable, HouseholdColumn),
	)
}
func newInvestmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvestmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InvestmentTable, InvestmentColumn),
	)
}
func newTransactionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TransactionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TransactionTable, TransactionColumn),
	)
}
