//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type FijoyCategory struct {
	ID           string `sql:"primary_key" json:"ID"`
	WorkspaceID  string `json:"WorkspaceID"`
	Name         string `json:"Name"`
	CategoryType string `json:"CategoryType"`
}
