[phases.setup]
nixPkgs = ['nodejs_20', 'corepack_20']

[phases.install]
# NOTE: https://vercel.com/guides/corepack-errors-github-actions#quick-debug-steps
cmds = ["npm install -g corepack@latest", "corepack enable", "pnpm install"]

[phases.build]
cmd = "pnpm build"

[start]
cmd = 'pnpm start'
