package beavermoney

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"time"

	"beavermoney.app/ent"
	"beavermoney.app/ent/currency"
	"beavermoney.app/ent/household"
	"beavermoney.app/ent/transaction"
	"beavermoney.app/ent/transactioncategory"
	"beavermoney.app/internal/contextkeys"
	"beavermoney.app/internal/gqlutil"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
)

// BalanceInHouseholdCurrency is the resolver for the balanceInHouseholdCurrency field.
func (r *accountResolver) BalanceInHouseholdCurrency(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Balance.Mul(obj.FxRate).String(), nil
}

// ValueInHouseholdCurrency is the resolver for the valueInHouseholdCurrency field.
func (r *accountResolver) ValueInHouseholdCurrency(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Value.Mul(obj.FxRate).String(), nil
}

// TotalIncome is the resolver for the totalIncome field.
func (r *financialReportResolver) TotalIncome(ctx context.Context, obj *FinancialReport) (string, error) {
	aggregates, err := r.aggregateByCategoryType(ctx, obj, transactioncategory.TypeIncome)
	if err != nil {
		return "0", err
	}

	if len(aggregates) == 0 {
		return "0", nil
	}

	return aggregates[0].Total, nil
}

// TotalExpenses is the resolver for the totalExpenses field.
func (r *financialReportResolver) TotalExpenses(ctx context.Context, obj *FinancialReport) (string, error) {
	aggregates, err := r.aggregateByCategoryType(ctx, obj, transactioncategory.TypeExpense)
	if err != nil {
		return "0", err
	}

	if len(aggregates) == 0 {
		return "0", nil
	}

	return aggregates[0].Total, nil
}

// IncomeByCategoryType is the resolver for the incomeByCategoryType field.
func (r *financialReportResolver) IncomeByCategoryType(ctx context.Context, obj *FinancialReport) ([]*CategoryTypeAggregate, error) {
	return r.aggregateByCategoryType(ctx, obj, transactioncategory.TypeIncome)
}

// ExpensesByCategoryType is the resolver for the expensesByCategoryType field.
func (r *financialReportResolver) ExpensesByCategoryType(ctx context.Context, obj *FinancialReport) ([]*CategoryTypeAggregate, error) {
	return r.aggregateByCategoryType(ctx, obj, transactioncategory.TypeExpense)
}

// TransactionCount is the resolver for the transactionCount field.
func (r *financialReportResolver) TransactionCount(ctx context.Context, obj *FinancialReport) (int, error) {
	householdID := contextkeys.GetHouseholdID(ctx)
	client := r.entClient

	query := client.Transaction.Query().
		Modify(func(s *sql.Selector) {
			// Filter by household
			s.Where(sql.EQ(s.C(transaction.FieldHouseholdID), householdID))

			// Apply time filters
			if !obj.StartDate.IsZero() {
				s.Where(sql.GTE(s.C(transaction.FieldDatetime), obj.StartDate))
			}
			if !obj.EndDate.IsZero() {
				s.Where(sql.LT(s.C(transaction.FieldDatetime), obj.EndDate))
			}
		})

	count, err := query.Count(ctx)
	if err != nil {
		r.logger.Error("Failed to count transactions", "error", err)
		return 0, err
	}

	return count, nil
}

// ValueInHouseholdCurrency is the resolver for the valueInHouseholdCurrency field.
func (r *investmentResolver) ValueInHouseholdCurrency(ctx context.Context, obj *ent.Investment) (string, error) {
	account, err := obj.QueryAccount().Only(ctx)
	if err != nil {
		return "", err
	}

	return obj.Value.Mul(account.FxRate).String(), nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input ent.CreateAccountInput) (*ent.AccountEdge, error) {
	now := time.Now()
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)
	zero := decimal.NewFromInt(0)

	household, err := r.entClient.Household.Query().Where(
		household.IDEQ(householdID),
	).WithCurrency().Only(ctx)
	if err != nil {
		return nil, err
	}

	accountCurrency, err := r.entClient.Currency.Query().Where(currency.IDEQ(input.CurrencyID)).Only(ctx)
	if err != nil {
		return nil, err
	}

	fxRate, err := r.fxrateClient.GetRate(ctx, accountCurrency.Code, household.Edges.Currency.Code, time.Now())
	if err != nil {
		return nil, err
	}

	account, err := client.Account.Create().
		SetInput(input).
		SetUserID(userID).
		SetHouseholdID(householdID).
		SetFxRate(fxRate).
		SetBalance(zero).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if input.Balance == nil || input.Balance.IsZero() {
		return &ent.AccountEdge{
			Node:   account,
			Cursor: gqlutil.EncodeCursor(account.ID),
		}, nil
	}

	categoryID, err := client.TransactionCategory.Create().
		SetHousehold(household).
		SetName("Setup").
		SetType(transactioncategory.TypeSetup).
		OnConflict(
			sql.ConflictColumns(
				transactioncategory.FieldName,
				transactioncategory.FieldHouseholdID,
			),
		).
		Ignore().
		ID(ctx)
	if err != nil {
		return nil, err
	}

	transaction, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetDescription("Initial Balance").
		SetDatetime(now).
		SetCategoryID(categoryID).
		SetUserID(userID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetAccount(account).
		SetAmount(*input.Balance).
		SetTransaction(transaction).
		SetCurrency(accountCurrency).
		Exec(ctx)
	if err != nil {
		return nil, err
	}

	account, err = client.Account.Get(ctx, account.ID)
	if err != nil {
		return nil, err
	}

	return &ent.AccountEdge{
		Node:   account,
		Cursor: gqlutil.EncodeCursor(account.ID),
	}, nil
}

// CreateInvestment is the resolver for the createInvestment field.
func (r *mutationResolver) CreateInvestment(ctx context.Context, input CreateInvestmentInputCustom) (*ent.InvestmentEdge, error) {
	now := time.Now()
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)
	zero := decimal.NewFromInt(0)

	account, err := client.Account.Get(ctx, input.Input.AccountID)
	if err != nil {
		return nil, err
	}

	if account.HouseholdID != householdID {
		return nil, fmt.Errorf("account does not belong to household")
	}

	quote, err := r.marketClient.EquityQuote(ctx, input.Input.Symbol)
	if err != nil {
		return nil, err
	}

	currencyID, err := client.Currency.Query().Where(currency.CodeEQ(quote.Currency)).OnlyID(ctx)
	if err != nil {
		return nil, err
	}

	investment, err := client.Investment.
		Create().
		SetInput(*input.Input).
		SetHouseholdID(householdID).
		SetAmount(zero).
		SetQuote(quote.CurrentPrice).
		SetValue(zero).
		SetCurrencyID(currencyID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if input.Input.Amount == nil || input.Input.Amount.IsZero() {
		return &ent.InvestmentEdge{
			Node:   investment,
			Cursor: gqlutil.EncodeCursor(investment.ID),
		}, nil
	}

	categoryID, err := client.TransactionCategory.Create().
		SetHouseholdID(householdID).
		SetName("Setup").
		SetType(transactioncategory.TypeSetup).
		OnConflict(
			sql.ConflictColumns(
				transactioncategory.FieldName,
				transactioncategory.FieldHouseholdID,
			),
		).
		Ignore().
		ID(ctx)
	if err != nil {
		return nil, err
	}

	transaction, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetDescription("Initial Value").
		SetDatetime(now).
		SetCategoryID(categoryID).
		SetUserID(userID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	costBasis, err := decimal.NewFromString(input.CostBasis)
	if err != nil {
		return nil, err
	}

	err = client.InvestmentLot.
		Create().
		SetAmount(*input.Input.Amount).
		SetPrice(costBasis).
		SetTransaction(transaction).
		SetInvestment(investment).
		SetHouseholdID(householdID).
		Exec(ctx)
	if err != nil {
		return nil, err
	}

	investment, err = client.Investment.Get(ctx, investment.ID)
	if err != nil {
		return nil, err
	}

	return &ent.InvestmentEdge{
		Node:   investment,
		Cursor: gqlutil.EncodeCursor(investment.ID),
	}, nil
}

// CreateTransactionCategory is the resolver for the createTransactionCategory field.
func (r *mutationResolver) CreateTransactionCategory(ctx context.Context, input ent.CreateTransactionCategoryInput) (*ent.TransactionCategoryEdge, error) {
	client := ent.FromContext(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	category, err := client.TransactionCategory.Create().
		SetHouseholdID(householdID).
		SetName(input.Name).
		SetType(transactioncategory.Type(input.Type)).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ent.TransactionCategoryEdge{
		Node:   category,
		Cursor: gqlutil.EncodeCursor(category.ID),
	}, nil
}

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input CreateExpenseInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	account, err := client.Account.Get(ctx, input.TransactionEntry.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	// Get currency for the account
	accountCurrency, err := account.QueryCurrency().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account currency: %w", err)
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Validate amount (should be negative for expense)
	amount := input.TransactionEntry.Amount
	if amount.IsPositive() {
		return nil, fmt.Errorf("expense amount must be negative")
	}

	// Create transaction entry for the expense
	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetAccountID(account.ID).
		SetCurrencyID(accountCurrency.ID).
		SetAmount(input.TransactionEntry.Amount).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction entry: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// CreateIncome is the resolver for the createIncome field.
func (r *mutationResolver) CreateIncome(ctx context.Context, input CreateIncomeInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate account belongs to household
	account, err := client.Account.Get(ctx, input.TransactionEntry.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	// Get currency for the account
	accountCurrency, err := account.QueryCurrency().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account currency: %w", err)
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Validate amount (should be positive for income)
	amount := input.TransactionEntry.Amount
	if amount.IsNegative() {
		return nil, fmt.Errorf("income amount must be positive")
	}

	// Create transaction entry for the income
	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetAccountID(account.ID).
		SetCurrencyID(accountCurrency.ID).
		SetAmount(amount).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction entry: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// CreateTransfer is the resolver for the createTransfer field.
func (r *mutationResolver) CreateTransfer(ctx context.Context, input CreateTransferInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate we have at least 2 transaction entries
	if len(input.TransactionEntries) < 2 {
		return nil, fmt.Errorf("transfer requires at least 2 transaction entries")
	}

	// Validate accounts belong to household and get currencies
	accountIDs := make(map[int]bool)
	for _, entry := range input.TransactionEntries {
		if accountIDs[entry.AccountID] {
			return nil, fmt.Errorf("cannot transfer to the same account")
		}
		accountIDs[entry.AccountID] = true

		_, err := client.Account.Get(ctx, entry.AccountID)
		if err != nil {
			return nil, fmt.Errorf("account not found: %w", err)
		}
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Create transaction entries
	for _, entry := range input.TransactionEntries {
		account, err := client.Account.Get(ctx, entry.AccountID)
		if err != nil {
			return nil, fmt.Errorf("account not found: %w", err)
		}

		accountCurrency, err := account.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(account.ID).
			SetCurrencyID(accountCurrency.ID).
			SetAmount(entry.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create transaction entry: %w", err)
		}
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// BuyInvestment is the resolver for the buyInvestment field.
func (r *mutationResolver) BuyInvestment(ctx context.Context, input BuyInvestmentInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate account belongs to household
	account, err := client.Account.Get(ctx, input.TransactionEntry.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	// Validate investment belongs to the account
	investment, err := client.Investment.Get(ctx, input.InvestmentLot.InvestmentID)
	if err != nil {
		return nil, fmt.Errorf("investment not found: %w", err)
	}
	if investment.AccountID != account.ID {
		return nil, fmt.Errorf("investment does not belong to account")
	}

	// Get currency for the account
	accountCurrency, err := account.QueryCurrency().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account currency: %w", err)
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Validate amount (should be negative for buying - cash going out)
	amount := input.TransactionEntry.Amount
	if amount.IsPositive() {
		return nil, fmt.Errorf("buy amount must be negative (cash going out)")
	}

	// Create transaction entry for the cash outflow
	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetAccountID(account.ID).
		SetCurrencyID(accountCurrency.ID).
		SetAmount(amount).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction entry: %w", err)
	}

	// Validate investment lot amount (should be positive - shares going in)
	if input.InvestmentLot.Amount.IsNegative() || input.InvestmentLot.Amount.IsZero() {
		return nil, fmt.Errorf("investment lot amount must be positive")
	}

	// Create investment lot
	err = client.InvestmentLot.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetInvestmentID(investment.ID).
		SetAmount(input.InvestmentLot.Amount).
		SetPrice(input.InvestmentLot.Price).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create investment lot: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// SellInvestment is the resolver for the sellInvestment field.
func (r *mutationResolver) SellInvestment(ctx context.Context, input SellInvestmentInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate account belongs to household
	account, err := client.Account.Get(ctx, input.TransactionEntry.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	// Validate investment belongs to the account
	investment, err := client.Investment.Get(ctx, input.InvestmentLot.InvestmentID)
	if err != nil {
		return nil, fmt.Errorf("investment not found: %w", err)
	}
	if investment.AccountID != account.ID {
		return nil, fmt.Errorf("investment does not belong to account")
	}

	// Get currency for the account
	accountCurrency, err := account.QueryCurrency().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account currency: %w", err)
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Validate amount (should be positive for selling - cash coming in)
	amount := input.TransactionEntry.Amount
	if amount.IsNegative() {
		return nil, fmt.Errorf("sell amount must be positive (cash coming in)")
	}

	// Create transaction entry for the cash inflow
	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetAccountID(account.ID).
		SetCurrencyID(accountCurrency.ID).
		SetAmount(amount).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction entry: %w", err)
	}

	// Validate investment lot amount (should be negative - shares going out)
	if input.InvestmentLot.Amount.IsPositive() || input.InvestmentLot.Amount.IsZero() {
		return nil, fmt.Errorf("investment lot amount must be negative (shares going out)")
	}

	// Create investment lot with negative amount
	err = client.InvestmentLot.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetInvestmentID(investment.ID).
		SetAmount(input.InvestmentLot.Amount).
		SetPrice(input.InvestmentLot.Price).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create investment lot: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// MoveInvestment is the resolver for the moveInvestment field.
func (r *mutationResolver) MoveInvestment(ctx context.Context, input MoveInvestmentInputCustom) (*ent.TransactionEdge, error) {
	panic(fmt.Errorf("not implemented: MoveInvestment - moveInvestment"))
}

// FxRate is the resolver for the fxRate field.
func (r *queryResolver) FxRate(ctx context.Context, from string, to string, datetime time.Time) (string, error) {
	rate, err := r.fxrateClient.GetRate(ctx, from, to, datetime)
	if err != nil {
		return "", err
	}

	return rate.String(), nil
}

// EquityQuote is the resolver for the equityQuote field.
func (r *queryResolver) EquityQuote(ctx context.Context, symbol string) (*EquityQuoteResult, error) {
	equityQuote, err := r.marketClient.EquityQuote(ctx, symbol)
	if err != nil {
		return nil, err
	}

	return &EquityQuoteResult{
		Symbol:       symbol,
		Name:         equityQuote.Name,
		Exchange:     equityQuote.Exchange,
		Currency:     equityQuote.Currency,
		CurrentPrice: equityQuote.CurrentPrice.String(),
	}, nil
}

// FinancialReport is the resolver for the financialReport field.
func (r *queryResolver) FinancialReport(ctx context.Context, period TimePeriodInput) (*FinancialReport, error) {
	// Parse time period
	start, end := parseTimePeriod(period)

	return &FinancialReport{
		StartDate: start,
		EndDate:   end,
	}, nil
}

// FinancialReport returns FinancialReportResolver implementation.
func (r *Resolver) FinancialReport() FinancialReportResolver { return &financialReportResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type financialReportResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) TransferInvestment(ctx context.Context, input TransferInvestmentInputCustom) (*ent.TransactionEdge, error) {
	panic(fmt.Errorf("not implemented: TransferInvestment - transferInvestment"))
}
*/
