package beavermoney

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"strings"
	"time"

	"beavermoney.app/ent"
	"beavermoney.app/ent/account"
	"beavermoney.app/ent/currency"
	"beavermoney.app/ent/household"
	"beavermoney.app/ent/investment"
	"beavermoney.app/ent/investmentlot"
	"beavermoney.app/ent/transaction"
	"beavermoney.app/ent/transactioncategory"
	"beavermoney.app/ent/userhousehold"
	"beavermoney.app/internal/contextkeys"
	"beavermoney.app/internal/gqlutil"
	"beavermoney.app/internal/seed"
	"entgo.io/ent/dialect/sql"
	"github.com/samber/lo"
	"github.com/shopspring/decimal"
)

// BalanceInHouseholdCurrency is the resolver for the balanceInHouseholdCurrency field.
func (r *accountResolver) BalanceInHouseholdCurrency(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Balance.Mul(obj.FxRate).String(), nil
}

// ValueInHouseholdCurrency is the resolver for the valueInHouseholdCurrency field.
func (r *accountResolver) ValueInHouseholdCurrency(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Value.Mul(obj.FxRate).String(), nil
}

// TotalIncome is the resolver for the totalIncome field.
func (r *financialReportResolver) TotalIncome(ctx context.Context, obj *FinancialReport) (string, error) {
	aggregates, err := r.aggregateByCategoryType(ctx, obj, transactioncategory.TypeIncome)
	if err != nil {
		return "0", err
	}

	if len(aggregates) == 0 {
		return "0", nil
	}

	return aggregates[0].Total, nil
}

// TotalExpenses is the resolver for the totalExpenses field.
func (r *financialReportResolver) TotalExpenses(ctx context.Context, obj *FinancialReport) (string, error) {
	aggregates, err := r.aggregateByCategoryType(ctx, obj, transactioncategory.TypeExpense)
	if err != nil {
		return "0", err
	}

	if len(aggregates) == 0 {
		return "0", nil
	}

	return aggregates[0].Total, nil
}

// IncomeByCategoryType is the resolver for the incomeByCategoryType field.
func (r *financialReportResolver) IncomeByCategoryType(ctx context.Context, obj *FinancialReport) ([]*CategoryTypeAggregate, error) {
	return r.aggregateByCategoryType(ctx, obj, transactioncategory.TypeIncome)
}

// ExpensesByCategoryType is the resolver for the expensesByCategoryType field.
func (r *financialReportResolver) ExpensesByCategoryType(ctx context.Context, obj *FinancialReport) ([]*CategoryTypeAggregate, error) {
	return r.aggregateByCategoryType(ctx, obj, transactioncategory.TypeExpense)
}

// TransactionCount is the resolver for the transactionCount field.
func (r *financialReportResolver) TransactionCount(ctx context.Context, obj *FinancialReport) (int, error) {
	householdID := contextkeys.GetHouseholdID(ctx)
	client := r.entClient

	query := client.Transaction.Query().
		Modify(func(s *sql.Selector) {
			// Filter by household
			s.Where(sql.EQ(s.C(transaction.FieldHouseholdID), householdID))

			// Apply time filters
			if !obj.StartDate.IsZero() {
				s.Where(sql.GTE(s.C(transaction.FieldDatetime), obj.StartDate))
			}
			if !obj.EndDate.IsZero() {
				s.Where(sql.LT(s.C(transaction.FieldDatetime), obj.EndDate))
			}
		})

	count, err := query.Count(ctx)
	if err != nil {
		r.logger.Error("Failed to count transactions", "error", err)
		return 0, err
	}

	return count, nil
}

// ValueInHouseholdCurrency is the resolver for the valueInHouseholdCurrency field.
func (r *investmentResolver) ValueInHouseholdCurrency(ctx context.Context, obj *ent.Investment) (string, error) {
	account, err := obj.QueryAccount().Only(ctx)
	if err != nil {
		return "", err
	}

	return obj.Value.Mul(account.FxRate).String(), nil
}

// CreateHousehold is the resolver for the createHousehold field.
func (r *mutationResolver) CreateHousehold(ctx context.Context, input ent.CreateHouseholdInput) (*ent.Household, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)

	// Create the household with a privacy bypass context since the user doesn't have
	// a household context yet
	bypassCtx := contextkeys.NewPrivacyBypassContext(ctx)

	household, err := client.Household.Create().
		SetInput(input).
		Save(bypassCtx)
	if err != nil {
		r.logger.Error("Failed to create household", "error", err)
		return nil, fmt.Errorf("failed to create household: %w", err)
	}

	// Create UserHousehold relationship (user is admin of the new household)
	err = client.UserHousehold.Create().
		SetUserID(userID).
		SetHouseholdID(household.ID).
		SetRole(userhousehold.RoleAdmin).
		Exec(bypassCtx)
	if err != nil {
		r.logger.Error("Failed to create user-household relationship", "error", err)
		return nil, fmt.Errorf("failed to create user-household relationship: %w", err)
	}

	ctx = context.WithValue(ctx, contextkeys.HouseholdIDKey(), household.ID)
	// Seed default transaction categories for the new household
	if err := seed.SeedHouseholdCategories(ctx, client, household.ID); err != nil {
		r.logger.Error("Failed to seed household categories", "error", err)
		return nil, fmt.Errorf("failed to seed household categories: %w", err)
	}

	return household, nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input ent.CreateAccountInput) (*ent.AccountEdge, error) {
	now := time.Now()
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)
	zero := decimal.NewFromInt(0)

	household, err := r.entClient.Household.Query().Where(
		household.IDEQ(householdID),
	).WithCurrency().Only(ctx)
	if err != nil {
		return nil, err
	}

	accountCurrency, err := r.entClient.Currency.Query().Where(currency.IDEQ(input.CurrencyID)).Only(ctx)
	if err != nil {
		return nil, err
	}

	fxRate, err := r.fxrateClient.GetRate(ctx, accountCurrency.Code, household.Edges.Currency.Code, time.Now())
	if err != nil {
		return nil, err
	}

	account, err := client.Account.Create().
		SetInput(input).
		SetUserID(userID).
		SetHouseholdID(householdID).
		SetFxRate(fxRate).
		SetBalance(zero).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if input.Balance == nil || input.Balance.IsZero() {
		return &ent.AccountEdge{
			Node:   account,
			Cursor: gqlutil.EncodeCursor(account.ID),
		}, nil
	}

	categoryID, err := client.TransactionCategory.Create().
		SetHousehold(household).
		SetName("Setup").
		SetType(transactioncategory.TypeSetup).
		OnConflict(
			sql.ConflictColumns(
				transactioncategory.FieldName,
				transactioncategory.FieldHouseholdID,
			),
		).
		Ignore().
		ID(ctx)
	if err != nil {
		return nil, err
	}

	transaction, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetDescription("Initial Balance").
		SetDatetime(now).
		SetCategoryID(categoryID).
		SetUserID(userID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetAccount(account).
		SetAmount(*input.Balance).
		SetTransaction(transaction).
		SetCurrency(accountCurrency).
		Exec(ctx)
	if err != nil {
		return nil, err
	}

	account, err = client.Account.Get(ctx, account.ID)
	if err != nil {
		return nil, err
	}

	return &ent.AccountEdge{
		Node:   account,
		Cursor: gqlutil.EncodeCursor(account.ID),
	}, nil
}

// CreateInvestment is the resolver for the createInvestment field.
func (r *mutationResolver) CreateInvestment(ctx context.Context, input CreateInvestmentInputCustom) (*ent.InvestmentEdge, error) {
	now := time.Now()
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)
	zero := decimal.NewFromInt(0)

	account, err := client.Account.Query().Where(account.IDEQ(input.Input.AccountID)).WithCurrency().Only(ctx)
	if err != nil {
		return nil, err
	}

	if account.HouseholdID != householdID {
		return nil, fmt.Errorf("account does not belong to household")
	}

	// Uppercase the symbol before querying
	symbolUpper := strings.ToUpper(input.Input.Symbol)

	quote, err := r.marketClient.StockQuote(ctx, symbolUpper)
	if err != nil {
		return nil, err
	}

	if quote.Currency != account.Edges.Currency.Code {
		return nil, fmt.Errorf("investment currency %s does not match account currency %s", quote.Currency, account.Edges.Currency.Code)
	}

	currencyID, err := client.Currency.Query().Where(currency.CodeEQ(quote.Currency)).OnlyID(ctx)
	if err != nil {
		return nil, err
	}

	// Set the symbol to uppercase
	input.Input.Symbol = symbolUpper

	investment, err := client.Investment.
		Create().
		SetInput(*input.Input).
		SetHouseholdID(householdID).
		SetAmount(zero).
		SetQuote(quote.CurrentPrice).
		SetValue(zero).
		SetCurrencyID(currencyID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	if input.Input.Amount == nil || input.Input.Amount.IsZero() {
		return &ent.InvestmentEdge{
			Node:   investment,
			Cursor: gqlutil.EncodeCursor(investment.ID),
		}, nil
	}

	categoryID, err := client.TransactionCategory.Create().
		SetHouseholdID(householdID).
		SetName("Setup").
		SetType(transactioncategory.TypeSetup).
		OnConflict(
			sql.ConflictColumns(
				transactioncategory.FieldName,
				transactioncategory.FieldHouseholdID,
			),
		).
		Ignore().
		ID(ctx)
	if err != nil {
		return nil, err
	}

	transaction, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetDescription("Initial Value").
		SetDatetime(now).
		SetCategoryID(categoryID).
		SetUserID(userID).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	costBasis, err := decimal.NewFromString(input.CostBasis)
	if err != nil {
		return nil, err
	}

	err = client.InvestmentLot.
		Create().
		SetAmount(*input.Input.Amount).
		SetPrice(costBasis).
		SetTransaction(transaction).
		SetInvestment(investment).
		SetHouseholdID(householdID).
		Exec(ctx)
	if err != nil {
		return nil, err
	}

	investment, err = client.Investment.Get(ctx, investment.ID)
	if err != nil {
		return nil, err
	}

	return &ent.InvestmentEdge{
		Node:   investment,
		Cursor: gqlutil.EncodeCursor(investment.ID),
	}, nil
}

// CreateTransactionCategory is the resolver for the createTransactionCategory field.
func (r *mutationResolver) CreateTransactionCategory(ctx context.Context, input ent.CreateTransactionCategoryInput) (*ent.TransactionCategoryEdge, error) {
	client := ent.FromContext(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	category, err := client.TransactionCategory.Create().
		SetHouseholdID(householdID).
		SetInput(input).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ent.TransactionCategoryEdge{
		Node:   category,
		Cursor: gqlutil.EncodeCursor(category.ID),
	}, nil
}

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input CreateExpenseInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	account, err := client.Account.Get(ctx, input.TransactionEntry.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	// Get currency for the account
	accountCurrency, err := account.QueryCurrency().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account currency: %w", err)
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Validate amount (should be negative for expense)
	amount := input.TransactionEntry.Amount
	if amount.IsPositive() {
		return nil, fmt.Errorf("expense amount must be negative")
	}

	// Create transaction entry for the expense
	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetAccountID(account.ID).
		SetCurrencyID(accountCurrency.ID).
		SetAmount(input.TransactionEntry.Amount).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction entry: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// CreateIncome is the resolver for the createIncome field.
func (r *mutationResolver) CreateIncome(ctx context.Context, input CreateIncomeInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate account belongs to household
	account, err := client.Account.Get(ctx, input.TransactionEntry.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	// Get currency for the account
	accountCurrency, err := account.QueryCurrency().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account currency: %w", err)
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Validate amount (should be positive for income)
	amount := input.TransactionEntry.Amount
	if amount.IsNegative() {
		return nil, fmt.Errorf("income amount must be positive")
	}

	// Create transaction entry for the income
	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetAccountID(account.ID).
		SetCurrencyID(accountCurrency.ID).
		SetAmount(amount).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction entry: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// CreateTransfer is the resolver for the createTransfer field.
func (r *mutationResolver) CreateTransfer(ctx context.Context, input CreateTransferInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate we have at least 2 transaction entries
	if len(input.TransactionEntries) < 2 {
		return nil, fmt.Errorf("transfer requires at least 2 transaction entries")
	}

	// Validate accounts belong to household and get currencies
	accountIDs := make(map[int]bool)
	for _, entry := range input.TransactionEntries {
		if accountIDs[entry.AccountID] {
			return nil, fmt.Errorf("cannot transfer to the same account")
		}
		accountIDs[entry.AccountID] = true

		_, err := client.Account.Get(ctx, entry.AccountID)
		if err != nil {
			return nil, fmt.Errorf("account not found: %w", err)
		}
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Create transaction entries
	for _, entry := range input.TransactionEntries {
		account, err := client.Account.Get(ctx, entry.AccountID)
		if err != nil {
			return nil, fmt.Errorf("account not found: %w", err)
		}

		accountCurrency, err := account.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(account.ID).
			SetCurrencyID(accountCurrency.ID).
			SetAmount(entry.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create transaction entry: %w", err)
		}
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// BuyInvestment is the resolver for the buyInvestment field.
func (r *mutationResolver) BuyInvestment(ctx context.Context, input BuyInvestmentInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate account belongs to household
	account, err := client.Account.Get(ctx, input.TransactionEntry.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	// Validate investment belongs to the account
	investment, err := client.Investment.Get(ctx, input.InvestmentLot.InvestmentID)
	if err != nil {
		return nil, fmt.Errorf("investment not found: %w", err)
	}
	if investment.AccountID != account.ID {
		return nil, fmt.Errorf("investment does not belong to account")
	}

	// Get currency for the account
	accountCurrency, err := account.QueryCurrency().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account currency: %w", err)
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Validate amount (should be negative for buying - cash going out)
	amount := input.TransactionEntry.Amount
	if amount.IsPositive() {
		return nil, fmt.Errorf("buy amount must be negative (cash going out)")
	}

	// Create transaction entry for the cash outflow
	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetAccountID(account.ID).
		SetCurrencyID(accountCurrency.ID).
		SetAmount(amount).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction entry: %w", err)
	}

	// Validate investment lot amount (should be positive - shares going in)
	if input.InvestmentLot.Amount.IsNegative() || input.InvestmentLot.Amount.IsZero() {
		return nil, fmt.Errorf("investment lot amount must be positive")
	}

	// Create investment lot
	err = client.InvestmentLot.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetInvestmentID(investment.ID).
		SetAmount(input.InvestmentLot.Amount).
		SetPrice(input.InvestmentLot.Price).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create investment lot: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// SellInvestment is the resolver for the sellInvestment field.
func (r *mutationResolver) SellInvestment(ctx context.Context, input SellInvestmentInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate account belongs to household
	account, err := client.Account.Get(ctx, input.TransactionEntry.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	// Validate investment belongs to the account
	investment, err := client.Investment.Get(ctx, input.InvestmentLot.InvestmentID)
	if err != nil {
		return nil, fmt.Errorf("investment not found: %w", err)
	}
	if investment.AccountID != account.ID {
		return nil, fmt.Errorf("investment does not belong to account")
	}

	// Get currency for the account
	accountCurrency, err := account.QueryCurrency().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account currency: %w", err)
	}

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Validate amount (should be positive for selling - cash coming in)
	amount := input.TransactionEntry.Amount
	if amount.IsNegative() {
		return nil, fmt.Errorf("sell amount must be positive (cash coming in)")
	}

	// Create transaction entry for the cash inflow
	err = client.TransactionEntry.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetAccountID(account.ID).
		SetCurrencyID(accountCurrency.ID).
		SetAmount(amount).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction entry: %w", err)
	}

	// Validate investment lot amount (should be negative - shares going out)
	if input.InvestmentLot.Amount.IsPositive() || input.InvestmentLot.Amount.IsZero() {
		return nil, fmt.Errorf("investment lot amount must be negative (shares going out)")
	}

	// Create investment lot with negative amount
	err = client.InvestmentLot.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetInvestmentID(investment.ID).
		SetAmount(input.InvestmentLot.Amount).
		SetPrice(input.InvestmentLot.Price).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create investment lot: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// MoveInvestment is the resolver for the moveInvestment field.
func (r *mutationResolver) MoveInvestment(ctx context.Context, input MoveInvestmentInputCustom) (*ent.TransactionEdge, error) {
	client := ent.FromContext(ctx)
	userID := contextkeys.GetUserID(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)

	// Validate we have exactly 2 lots (from and to)
	if len(input.InvestmentLots) != 2 {
		return nil, fmt.Errorf("move investment requires exactly 2 investment lots")
	}

	// Find from lot (negative amount) and to lot (positive amount)
	var fromLot, toLot *ent.CreateInvestmentLotInput
	for i := range input.InvestmentLots {
		lot := input.InvestmentLots[i]
		if lot.Amount.IsNegative() {
			fromLot = lot
		} else if lot.Amount.IsPositive() {
			toLot = lot
		}
	}

	// Validate from and to lots
	if fromLot == nil || toLot == nil || fromLot.InvestmentID == 0 || toLot.InvestmentID == 0 {
		return nil, fmt.Errorf("invalid investment lots: must have one negative (from) and one positive (to)")
	}

	// Validate amounts match
	if !fromLot.Amount.Abs().Equal(toLot.Amount) {
		return nil, fmt.Errorf("from and to amounts must match")
	}

	// Get investments and validate they belong to household and have same symbol
	fromInvestment, err := client.Investment.Get(ctx, fromLot.InvestmentID)
	if err != nil {
		return nil, fmt.Errorf("from investment not found: %w", err)
	}

	toInvestment, err := client.Investment.Get(ctx, toLot.InvestmentID)
	if err != nil {
		return nil, fmt.Errorf("to investment not found: %w", err)
	}

	// Validate both investments belong to household
	fromAccount, err := fromInvestment.QueryAccount().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get from account: %w", err)
	}
	if fromAccount.HouseholdID != householdID {
		return nil, fmt.Errorf("from investment does not belong to household")
	}

	toAccount, err := toInvestment.QueryAccount().Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get to account: %w", err)
	}
	if toAccount.HouseholdID != householdID {
		return nil, fmt.Errorf("to investment does not belong to household")
	}

	// Validate same symbol
	if fromInvestment.Symbol != toInvestment.Symbol {
		return nil, fmt.Errorf("investments must have the same symbol")
	}

	// Calculate average price from fromInvestment
	// Query all lots for the from investment to calculate average price
	lots, err := client.InvestmentLot.Query().
		Where(investmentlot.InvestmentID(fromInvestment.ID)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to query investment lots: %w", err)
	}

	totalShares := decimal.Zero
	totalCost := decimal.Zero
	for _, lot := range lots {
		totalShares = totalShares.Add(lot.Amount)
		totalCost = totalCost.Add(lot.Amount.Mul(lot.Price))
	}

	if totalShares.IsZero() || totalShares.IsNegative() {
		return nil, fmt.Errorf("insufficient shares in from investment")
	}

	// Check if we have enough shares to move
	if totalShares.LessThan(toLot.Amount) {
		return nil, fmt.Errorf("insufficient shares: have %s, trying to move %s", totalShares.String(), toLot.Amount.String())
	}

	averagePrice := totalCost.Div(totalShares)

	// Create transaction
	txn, err := client.Transaction.Create().
		SetHouseholdID(householdID).
		SetUserID(userID).
		SetInput(*input.Transaction).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create transaction: %w", err)
	}

	// Create investment lot for outgoing shares (negative)
	err = client.InvestmentLot.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetInvestmentID(fromInvestment.ID).
		SetAmount(fromLot.Amount).
		SetPrice(averagePrice).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create from investment lot: %w", err)
	}

	// Create investment lot for incoming shares (positive)
	err = client.InvestmentLot.Create().
		SetHouseholdID(householdID).
		SetTransactionID(txn.ID).
		SetInvestmentID(toInvestment.ID).
		SetAmount(toLot.Amount).
		SetPrice(averagePrice).
		Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create to investment lot: %w", err)
	}

	// Create fee entries if any
	for _, fee := range input.Fees {
		feeAccount, err := client.Account.Get(ctx, fee.AccountID)
		if err != nil {
			return nil, fmt.Errorf("fee account not found: %w", err)
		}
		if feeAccount.HouseholdID != householdID {
			return nil, fmt.Errorf("fee account does not belong to household")
		}

		feeCurrency, err := feeAccount.QueryCurrency().Only(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get fee account currency: %w", err)
		}

		err = client.TransactionEntry.Create().
			SetHouseholdID(householdID).
			SetTransactionID(txn.ID).
			SetAccountID(feeAccount.ID).
			SetCurrencyID(feeCurrency.ID).
			SetAmount(fee.Amount).
			Exec(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to create fee entry: %w", err)
		}
	}

	// Reload transaction to get updated data
	txn, err = client.Transaction.Get(ctx, txn.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload transaction: %w", err)
	}

	return &ent.TransactionEdge{
		Node:   txn,
		Cursor: gqlutil.EncodeCursor(txn.ID),
	}, nil
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context) (bool, error) {
	client := ent.FromContext(ctx)
	householdID := contextkeys.GetHouseholdID(ctx)
	now := time.Now()

	// Get household with currency
	household, err := client.Household.Query().
		Where(household.IDEQ(householdID)).
		WithCurrency().
		Only(ctx)
	if err != nil {
		r.logger.Error("Failed to fetch household", "error", err)
		return false, err
	}

	householdCurrencyCode := household.Edges.Currency.Code

	// Fetch all accounts for the household with their currencies
	accounts, err := client.Account.Query().
		WithCurrency().
		All(ctx)
	if err != nil {
		r.logger.Error("Failed to fetch accounts", "error", err)
		return false, err
	}

	// Group accounts by currency to minimize FX rate API calls
	currencyToAccounts := lo.GroupBy(accounts, func(account *ent.Account) string {
		return account.Edges.Currency.Code
	})

	// Get unique currencies excluding household currency
	uniqueCurrencies := lo.Filter(lo.Keys(currencyToAccounts), func(code string, _ int) bool {
		return code != householdCurrencyCode
	})

	// Batch fetch FX rates for all unique currencies
	if len(uniqueCurrencies) > 0 {
		rates, err := r.fxrateClient.GetRates(ctx, uniqueCurrencies, householdCurrencyCode, now)
		if err != nil {
			r.logger.Error("Failed to fetch FX rates", "error", err)
			return false, err
		}

		// Update accounts with new FX rates
		for currencyCode, accountList := range currencyToAccounts {
			var fxRate decimal.Decimal
			if currencyCode == householdCurrencyCode {
				fxRate = decimal.NewFromInt(1)
			} else {
				rate, ok := rates[currencyCode]
				if !ok {
					r.logger.Error("FX rate not found for currency", "currency", currencyCode)
					continue
				}
				fxRate = rate
			}

			// Update all accounts with this currency
			for _, account := range accountList {
				err := client.Account.UpdateOneID(account.ID).
					SetFxRate(fxRate).
					Exec(ctx)
				if err != nil {
					r.logger.Error("Failed to update account FX rate", "error", err, "accountID", account.ID)
					return false, err
				}
			}
		}
	}

	// Fetch all investments for the household
	investments, err := client.Investment.Query().
		All(ctx)
	if err != nil {
		r.logger.Error("Failed to fetch investments", "error", err)
		return false, err
	}

	if len(investments) == 0 {
		return true, nil
	}

	// Group investments by type (stock vs crypto)
	stockInvestments := lo.GroupBy(
		lo.Filter(investments, func(inv *ent.Investment, _ int) bool {
			return inv.Type == investment.TypeStock
		}),
		func(inv *ent.Investment) string {
			return strings.ToUpper(inv.Symbol)
		},
	)

	cryptoInvestments := lo.GroupBy(
		lo.Filter(investments, func(inv *ent.Investment, _ int) bool {
			return inv.Type == investment.TypeCrypto
		}),
		func(inv *ent.Investment) string {
			return strings.ToUpper(inv.Symbol)
		},
	)

	stockSymbols := lo.Keys(stockInvestments)
	cryptoSymbols := lo.Keys(cryptoInvestments)

	// Batch fetch stock quotes
	if len(stockSymbols) > 0 {
		quotes, err := r.marketClient.StockQuotes(ctx, stockSymbols)
		if err != nil {
			r.logger.Error("Failed to fetch stock quotes", "error", err)
			return false, err
		}

		// Update investments with new quotes
		for symbol, invList := range stockInvestments {
			quote, ok := quotes[symbol]
			if !ok {
				r.logger.Error("Stock quote not found for symbol", "symbol", symbol)
				continue
			}

			for _, inv := range invList {
				err := client.Investment.UpdateOneID(inv.ID).
					SetQuote(quote.CurrentPrice).
					Exec(ctx)
				if err != nil {
					r.logger.Error("Failed to update investment quote", "error", err, "investmentID", inv.ID)
					return false, err
				}
			}
		}
	}

	// Batch fetch crypto quotes
	if len(cryptoSymbols) > 0 {
		quotes, err := r.marketClient.CryptoQuotes(ctx, cryptoSymbols)
		if err != nil {
			r.logger.Error("Failed to fetch crypto quotes", "error", err)
			return false, err
		}

		// Update investments with new quotes
		for symbol, invList := range cryptoInvestments {
			quote, ok := quotes[symbol]
			if !ok {
				r.logger.Error("Crypto quote not found for symbol", "symbol", symbol)
				continue
			}

			for _, inv := range invList {
				err := client.Investment.UpdateOneID(inv.ID).
					SetQuote(quote.CurrentPrice).
					Exec(ctx)
				if err != nil {
					r.logger.Error("Failed to update investment quote", "error", err, "investmentID", inv.ID)
					return false, err
				}
			}
		}
	}

	return true, nil
}

// FxRate is the resolver for the fxRate field.
func (r *queryResolver) FxRate(ctx context.Context, from string, to string, datetime time.Time) (string, error) {
	rate, err := r.fxrateClient.GetRate(ctx, from, to, datetime)
	if err != nil {
		return "", err
	}

	return rate.String(), nil
}

// StockQuote is the resolver for the stockQuote field.
func (r *queryResolver) StockQuote(ctx context.Context, symbol string) (*StockQuoteResult, error) {
	stockQuote, err := r.marketClient.StockQuote(ctx, symbol)
	if err != nil {
		return nil, err
	}

	return &StockQuoteResult{
		Symbol:       symbol,
		Name:         stockQuote.Name,
		Exchange:     stockQuote.Exchange,
		Currency:     stockQuote.Currency,
		CurrentPrice: stockQuote.CurrentPrice.String(),
	}, nil
}

// CryptoQuote is the resolver for the cryptoQuote field.
func (r *queryResolver) CryptoQuote(ctx context.Context, symbol string) (*CryptoQuoteResult, error) {
	cryptoQuote, err := r.marketClient.CryptoQuote(ctx, symbol)
	if err != nil {
		return nil, err
	}

	return &CryptoQuoteResult{
		Symbol:       symbol,
		Name:         cryptoQuote.Name,
		Exchange:     cryptoQuote.Exchange,
		Currency:     cryptoQuote.Currency,
		CurrentPrice: cryptoQuote.CurrentPrice.String(),
	}, nil
}

// FinancialReport is the resolver for the financialReport field.
func (r *queryResolver) FinancialReport(ctx context.Context, period TimePeriodInput) (*FinancialReport, error) {
	// Parse time period
	start, end := parseTimePeriod(period)

	return &FinancialReport{
		StartDate: start,
		EndDate:   end,
	}, nil
}

// FinancialReport returns FinancialReportResolver implementation.
func (r *Resolver) FinancialReport() FinancialReportResolver { return &financialReportResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type financialReportResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
