package fijoy

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"fijoy/ent"
	"fijoy/ent/account"
	"fijoy/ent/profile"
	"fijoy/ent/transaction"
	"fijoy/ent/user"
	"fijoy/internal/util/auth"
	"fmt"

	"entgo.io/contrib/entgql"
	"github.com/shopspring/decimal"
)

// Amount is the resolver for the amount field.
func (r *accountResolver) Amount(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Amount.String(), nil
}

// Value is the resolver for the value field.
func (r *accountResolver) Value(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Value.String(), nil
}

// Balance is the resolver for the balance field.
func (r *accountResolver) Balance(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Balance.String(), nil
}

// NetWorthGoal is the resolver for the netWorthGoal field.
func (r *profileResolver) NetWorthGoal(ctx context.Context, obj *ent.Profile) (string, error) {
	return obj.NetWorthGoal.String(), nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int) (*ent.AccountConnection, error) {
	authData, err := auth.GetAuthDataFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.client.Account.Query().
		Where(account.HasProfileWith(profile.ID(authData.ProfileID))).
		Paginate(ctx, after, first, before, last)
}

// Profiles is the resolver for the profiles field.
func (r *queryResolver) Profiles(ctx context.Context) ([]*ent.Profile, error) {
	authData, err := auth.GetUserDataFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.client.Profile.Query().Where(profile.HasUsersWith(user.ID(authData.UserID))).All(ctx)
}

// Snapshots is the resolver for the snapshots field.
func (r *queryResolver) Snapshots(ctx context.Context) ([]*ent.Snapshot, error) {
	panic(fmt.Errorf("not implemented: Snapshots - snapshots"))
}

// SnapshotAccounts is the resolver for the snapshotAccounts field.
func (r *queryResolver) SnapshotAccounts(ctx context.Context) ([]*ent.SnapshotAccount, error) {
	panic(fmt.Errorf("not implemented: SnapshotAccounts - snapshotAccounts"))
}

// SnapshotFxRates is the resolver for the snapshotFxRates field.
func (r *queryResolver) SnapshotFxRates(ctx context.Context) ([]*ent.SnapshotFXRate, error) {
	panic(fmt.Errorf("not implemented: SnapshotFxRates - snapshotFxRates"))
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int) (*ent.TransactionConnection, error) {
	authData, err := auth.GetAuthDataFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.client.Transaction.Query().
		Where(transaction.HasProfileWith(profile.ID(authData.ProfileID))).
		Order(ent.Desc(transaction.FieldCreateTime)).
		Paginate(ctx, after, first, before, last)
}

// Amount is the resolver for the amount field.
func (r *snapshotAccountResolver) Amount(ctx context.Context, obj *ent.SnapshotAccount) (string, error) {
	panic(fmt.Errorf("not implemented: Amount - amount"))
}

// Value is the resolver for the value field.
func (r *snapshotAccountResolver) Value(ctx context.Context, obj *ent.SnapshotAccount) (string, error) {
	panic(fmt.Errorf("not implemented: Value - value"))
}

// Balance is the resolver for the balance field.
func (r *snapshotAccountResolver) Balance(ctx context.Context, obj *ent.SnapshotAccount) (string, error) {
	panic(fmt.Errorf("not implemented: Balance - balance"))
}

// FxRate is the resolver for the fxRate field.
func (r *snapshotFXRateResolver) FxRate(ctx context.Context, obj *ent.SnapshotFXRate) (string, error) {
	panic(fmt.Errorf("not implemented: FxRate - fxRate"))
}

// Amount is the resolver for the amount field.
func (r *transactionEntryResolver) Amount(ctx context.Context, obj *ent.TransactionEntry) (string, error) {
	return obj.Amount.String(), nil
}

// Value is the resolver for the value field.
func (r *transactionEntryResolver) Value(ctx context.Context, obj *ent.TransactionEntry) (string, error) {
	return obj.Value.String(), nil
}

// Balance is the resolver for the balance field.
func (r *transactionEntryResolver) Balance(ctx context.Context, obj *ent.TransactionEntry) (string, error) {
	return obj.Balance.String(), nil
}

// Amount is the resolver for the amount field.
func (r *createAccountInputResolver) Amount(ctx context.Context, obj *ent.CreateAccountInput, data string) error {
	if data == "" {
		return errors.New("amount is required")
	}

	dec, err := decimal.NewFromString(data)
	if err != nil {
		return fmt.Errorf("invalid amount: %w", err)
	}

	obj.Amount = dec
	return nil
}

// NetWorthGoal is the resolver for the netWorthGoal field.
func (r *createProfileInputResolver) NetWorthGoal(ctx context.Context, obj *ent.CreateProfileInput, data string) error {
	if data == "" {
		return errors.New("net worth goal is required")
	}

	dec, err := decimal.NewFromString(data)
	if err != nil {
		return fmt.Errorf("invalid net worth goal: %w", err)
	}

	obj.NetWorthGoal = dec
	return nil
}

// Amount is the resolver for the amount field.
func (r *createTransactionEntryInputResolver) Amount(ctx context.Context, obj *ent.CreateTransactionEntryInput, data string) error {
	if data == "" {
		return errors.New("amount is required")
	}

	dec, err := decimal.NewFromString(data)
	if err != nil {
		return fmt.Errorf("invalid amount: %w", err)
	}

	obj.Amount = dec
	return nil
}

// Amount is the resolver for the amount field.
func (r *updateAccountInputResolver) Amount(ctx context.Context, obj *ent.UpdateAccountInput, data *string) error {
	if data == nil || *data == "" {
		return nil
	}

	dec, err := decimal.NewFromString(*data)
	if err != nil {
		return fmt.Errorf("invalid amount: %w", err)
	}

	obj.Amount = &dec
	return nil
}

// NetWorthGoal is the resolver for the netWorthGoal field.
func (r *updateProfileInputResolver) NetWorthGoal(ctx context.Context, obj *ent.UpdateProfileInput, data *string) error {
	if data == nil || *data == "" {
		return nil
	}

	dec, err := decimal.NewFromString(*data)
	if err != nil {
		return fmt.Errorf("invalid net worth goal: %w", err)
	}

	obj.NetWorthGoal = &dec
	return nil
}

// Amount is the resolver for the amount field.
func (r *updateTransactionEntryInputResolver) Amount(ctx context.Context, obj *ent.UpdateTransactionEntryInput, data *string) error {
	if data == nil || *data == "" {
		return nil
	}

	dec, err := decimal.NewFromString(*data)
	if err != nil {
		return fmt.Errorf("invalid amount: %w", err)
	}

	obj.Amount = &dec
	return nil
}

// Account returns AccountResolver implementation.
func (r *Resolver) Account() AccountResolver { return &accountResolver{r} }

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SnapshotAccount returns SnapshotAccountResolver implementation.
func (r *Resolver) SnapshotAccount() SnapshotAccountResolver { return &snapshotAccountResolver{r} }

// SnapshotFXRate returns SnapshotFXRateResolver implementation.
func (r *Resolver) SnapshotFXRate() SnapshotFXRateResolver { return &snapshotFXRateResolver{r} }

// TransactionEntry returns TransactionEntryResolver implementation.
func (r *Resolver) TransactionEntry() TransactionEntryResolver { return &transactionEntryResolver{r} }

// CreateAccountInput returns CreateAccountInputResolver implementation.
func (r *Resolver) CreateAccountInput() CreateAccountInputResolver {
	return &createAccountInputResolver{r}
}

// CreateProfileInput returns CreateProfileInputResolver implementation.
func (r *Resolver) CreateProfileInput() CreateProfileInputResolver {
	return &createProfileInputResolver{r}
}

// CreateTransactionEntryInput returns CreateTransactionEntryInputResolver implementation.
func (r *Resolver) CreateTransactionEntryInput() CreateTransactionEntryInputResolver {
	return &createTransactionEntryInputResolver{r}
}

// UpdateAccountInput returns UpdateAccountInputResolver implementation.
func (r *Resolver) UpdateAccountInput() UpdateAccountInputResolver {
	return &updateAccountInputResolver{r}
}

// UpdateProfileInput returns UpdateProfileInputResolver implementation.
func (r *Resolver) UpdateProfileInput() UpdateProfileInputResolver {
	return &updateProfileInputResolver{r}
}

// UpdateTransactionEntryInput returns UpdateTransactionEntryInputResolver implementation.
func (r *Resolver) UpdateTransactionEntryInput() UpdateTransactionEntryInputResolver {
	return &updateTransactionEntryInputResolver{r}
}

type accountResolver struct{ *Resolver }
type profileResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type snapshotAccountResolver struct{ *Resolver }
type snapshotFXRateResolver struct{ *Resolver }
type transactionEntryResolver struct{ *Resolver }
type createAccountInputResolver struct{ *Resolver }
type createProfileInputResolver struct{ *Resolver }
type createTransactionEntryInputResolver struct{ *Resolver }
type updateAccountInputResolver struct{ *Resolver }
type updateProfileInputResolver struct{ *Resolver }
type updateTransactionEntryInputResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Categories(ctx context.Context) ([]*ent.Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}
*/
