set fallback

set dotenv-load := true

build:
  go build -o ./tmp/main ./cmd/fijoy/main.go

db-up:
  migrate -database ${DB_URL} -path ./migrations up

db-down:
  migrate -database ${DB_URL} -path ./migrations down

db-force version:
  migrate -database ${DB_URL} -path ./migrations force {{version}}

jet:
  go run ./cmd/jet/main.go

update:
  go mod tidy
  go get -u all

test:
  go test ./...

format:
  pnpm format

kill:
  pids=$(lsof -t -i :3000) && [ -n "$pids" ] && kill -9 $pids

init:
  go install github.com/air-verse/air@latest
  go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
