set fallback

set dotenv-load := true

build:
  go build -o ./tmp/main ./cmd/fijoy/main.go

update:
  go mod tidy
  go get -u all
  go mod tidy

test:
  go test ./...

format:
  pnpm format

kill:
  pids=$(lsof -t -i :3000) && [ -n "$pids" ] && kill -9 $pids

init:
  go install github.com/air-verse/air@latest

migrate-diff name:
  atlas migrate diff {{name}} \
  --dir "file://ent/migrate/migrations" \
  --to "ent://ent/schema" \
  --dev-url "docker://postgres/15/test?search_path=public"

migrate-lint:
  atlas migrate lint \
  --dev-url="docker://postgres/15/test?search_path=public" \
  --dir="file://ent/migrate/migrations" \
  --latest=1

ent-new name:
  go run -mod=mod entgo.io/ent/cmd/ent new {{name}}

ent-generate:
  go generate ./ent

ent-drop:
  go run ./cmd/ent/main.go
