// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"time"

	"beavermoney.app/ent/account"
	"beavermoney.app/ent/currency"
	"beavermoney.app/ent/household"
	"beavermoney.app/ent/investment"
	"beavermoney.app/ent/investmentlot"
	"beavermoney.app/ent/recurringsubscription"
	"beavermoney.app/ent/schema"
	"beavermoney.app/ent/transaction"
	"beavermoney.app/ent/transactioncategory"
	"beavermoney.app/ent/transactionentry"
	"beavermoney.app/ent/user"
	"beavermoney.app/ent/userhousehold"
	"beavermoney.app/ent/userkey"
	"github.com/shopspring/decimal"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	account.Policy = privacy.NewPolicies(accountMixin[1], schema.Account{})
	account.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := account.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreateTime is the schema descriptor for create_time field.
	accountDescCreateTime := accountMixinFields0[0].Descriptor()
	// account.DefaultCreateTime holds the default value on creation for the create_time field.
	account.DefaultCreateTime = accountDescCreateTime.Default.(func() time.Time)
	// accountDescUpdateTime is the schema descriptor for update_time field.
	accountDescUpdateTime := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdateTime holds the default value on creation for the update_time field.
	account.DefaultUpdateTime = accountDescUpdateTime.Default.(func() time.Time)
	// account.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	account.UpdateDefaultUpdateTime = accountDescUpdateTime.UpdateDefault.(func() time.Time)
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescBalance is the schema descriptor for balance field.
	accountDescBalance := accountFields[2].Descriptor()
	// account.DefaultBalance holds the default value on creation for the balance field.
	account.DefaultBalance = accountDescBalance.Default.(func() decimal.Decimal)
	// accountDescValue is the schema descriptor for value field.
	accountDescValue := accountFields[4].Descriptor()
	// account.DefaultValue holds the default value on creation for the value field.
	account.DefaultValue = accountDescValue.Default.(func() decimal.Decimal)
	// accountDescCurrencyID is the schema descriptor for currency_id field.
	accountDescCurrencyID := accountFields[6].Descriptor()
	// account.CurrencyIDValidator is a validator for the "currency_id" field. It is called by the builders before save.
	account.CurrencyIDValidator = accountDescCurrencyID.Validators[0].(func(int) error)
	// accountDescUserID is the schema descriptor for user_id field.
	accountDescUserID := accountFields[7].Descriptor()
	// account.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	account.UserIDValidator = accountDescUserID.Validators[0].(func(int) error)
	currencyFields := schema.Currency{}.Fields()
	_ = currencyFields
	// currencyDescCode is the schema descriptor for code field.
	currencyDescCode := currencyFields[0].Descriptor()
	// currency.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	currency.CodeValidator = currencyDescCode.Validators[0].(func(string) error)
	householdMixin := schema.Household{}.Mixin()
	household.Policy = privacy.NewPolicies(schema.Household{})
	household.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := household.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	householdMixinFields0 := householdMixin[0].Fields()
	_ = householdMixinFields0
	householdFields := schema.Household{}.Fields()
	_ = householdFields
	// householdDescCreateTime is the schema descriptor for create_time field.
	householdDescCreateTime := householdMixinFields0[0].Descriptor()
	// household.DefaultCreateTime holds the default value on creation for the create_time field.
	household.DefaultCreateTime = householdDescCreateTime.Default.(func() time.Time)
	// householdDescUpdateTime is the schema descriptor for update_time field.
	householdDescUpdateTime := householdMixinFields0[1].Descriptor()
	// household.DefaultUpdateTime holds the default value on creation for the update_time field.
	household.DefaultUpdateTime = householdDescUpdateTime.Default.(func() time.Time)
	// household.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	household.UpdateDefaultUpdateTime = householdDescUpdateTime.UpdateDefault.(func() time.Time)
	// householdDescName is the schema descriptor for name field.
	householdDescName := householdFields[0].Descriptor()
	// household.NameValidator is a validator for the "name" field. It is called by the builders before save.
	household.NameValidator = householdDescName.Validators[0].(func(string) error)
	// householdDescLocale is the schema descriptor for locale field.
	householdDescLocale := householdFields[1].Descriptor()
	// household.LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	household.LocaleValidator = householdDescLocale.Validators[0].(func(string) error)
	// householdDescCurrencyID is the schema descriptor for currency_id field.
	householdDescCurrencyID := householdFields[2].Descriptor()
	// household.CurrencyIDValidator is a validator for the "currency_id" field. It is called by the builders before save.
	household.CurrencyIDValidator = householdDescCurrencyID.Validators[0].(func(int) error)
	investmentMixin := schema.Investment{}.Mixin()
	investment.Policy = privacy.NewPolicies(investmentMixin[1], schema.Investment{})
	investment.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := investment.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	investmentMixinFields0 := investmentMixin[0].Fields()
	_ = investmentMixinFields0
	investmentFields := schema.Investment{}.Fields()
	_ = investmentFields
	// investmentDescCreateTime is the schema descriptor for create_time field.
	investmentDescCreateTime := investmentMixinFields0[0].Descriptor()
	// investment.DefaultCreateTime holds the default value on creation for the create_time field.
	investment.DefaultCreateTime = investmentDescCreateTime.Default.(func() time.Time)
	// investmentDescUpdateTime is the schema descriptor for update_time field.
	investmentDescUpdateTime := investmentMixinFields0[1].Descriptor()
	// investment.DefaultUpdateTime holds the default value on creation for the update_time field.
	investment.DefaultUpdateTime = investmentDescUpdateTime.Default.(func() time.Time)
	// investment.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	investment.UpdateDefaultUpdateTime = investmentDescUpdateTime.UpdateDefault.(func() time.Time)
	// investmentDescSymbol is the schema descriptor for symbol field.
	investmentDescSymbol := investmentFields[2].Descriptor()
	// investment.SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	investment.SymbolValidator = investmentDescSymbol.Validators[0].(func(string) error)
	// investmentDescAmount is the schema descriptor for amount field.
	investmentDescAmount := investmentFields[3].Descriptor()
	// investment.DefaultAmount holds the default value on creation for the amount field.
	investment.DefaultAmount = investmentDescAmount.Default.(func() decimal.Decimal)
	// investmentDescValue is the schema descriptor for value field.
	investmentDescValue := investmentFields[5].Descriptor()
	// investment.DefaultValue holds the default value on creation for the value field.
	investment.DefaultValue = investmentDescValue.Default.(func() decimal.Decimal)
	// investmentDescAccountID is the schema descriptor for account_id field.
	investmentDescAccountID := investmentFields[6].Descriptor()
	// investment.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	investment.AccountIDValidator = investmentDescAccountID.Validators[0].(func(int) error)
	// investmentDescCurrencyID is the schema descriptor for currency_id field.
	investmentDescCurrencyID := investmentFields[7].Descriptor()
	// investment.CurrencyIDValidator is a validator for the "currency_id" field. It is called by the builders before save.
	investment.CurrencyIDValidator = investmentDescCurrencyID.Validators[0].(func(int) error)
	investmentlotMixin := schema.InvestmentLot{}.Mixin()
	investmentlot.Policy = privacy.NewPolicies(investmentlotMixin[1], schema.InvestmentLot{})
	investmentlot.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := investmentlot.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	investmentlotMixinFields0 := investmentlotMixin[0].Fields()
	_ = investmentlotMixinFields0
	investmentlotFields := schema.InvestmentLot{}.Fields()
	_ = investmentlotFields
	// investmentlotDescCreateTime is the schema descriptor for create_time field.
	investmentlotDescCreateTime := investmentlotMixinFields0[0].Descriptor()
	// investmentlot.DefaultCreateTime holds the default value on creation for the create_time field.
	investmentlot.DefaultCreateTime = investmentlotDescCreateTime.Default.(func() time.Time)
	// investmentlotDescUpdateTime is the schema descriptor for update_time field.
	investmentlotDescUpdateTime := investmentlotMixinFields0[1].Descriptor()
	// investmentlot.DefaultUpdateTime holds the default value on creation for the update_time field.
	investmentlot.DefaultUpdateTime = investmentlotDescUpdateTime.Default.(func() time.Time)
	// investmentlot.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	investmentlot.UpdateDefaultUpdateTime = investmentlotDescUpdateTime.UpdateDefault.(func() time.Time)
	// investmentlotDescInvestmentID is the schema descriptor for investment_id field.
	investmentlotDescInvestmentID := investmentlotFields[2].Descriptor()
	// investmentlot.InvestmentIDValidator is a validator for the "investment_id" field. It is called by the builders before save.
	investmentlot.InvestmentIDValidator = investmentlotDescInvestmentID.Validators[0].(func(int) error)
	// investmentlotDescTransactionID is the schema descriptor for transaction_id field.
	investmentlotDescTransactionID := investmentlotFields[3].Descriptor()
	// investmentlot.TransactionIDValidator is a validator for the "transaction_id" field. It is called by the builders before save.
	investmentlot.TransactionIDValidator = investmentlotDescTransactionID.Validators[0].(func(int) error)
	recurringsubscriptionMixin := schema.RecurringSubscription{}.Mixin()
	recurringsubscription.Policy = privacy.NewPolicies(recurringsubscriptionMixin[1], schema.RecurringSubscription{})
	recurringsubscription.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := recurringsubscription.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	recurringsubscriptionMixinFields0 := recurringsubscriptionMixin[0].Fields()
	_ = recurringsubscriptionMixinFields0
	recurringsubscriptionFields := schema.RecurringSubscription{}.Fields()
	_ = recurringsubscriptionFields
	// recurringsubscriptionDescCreateTime is the schema descriptor for create_time field.
	recurringsubscriptionDescCreateTime := recurringsubscriptionMixinFields0[0].Descriptor()
	// recurringsubscription.DefaultCreateTime holds the default value on creation for the create_time field.
	recurringsubscription.DefaultCreateTime = recurringsubscriptionDescCreateTime.Default.(func() time.Time)
	// recurringsubscriptionDescUpdateTime is the schema descriptor for update_time field.
	recurringsubscriptionDescUpdateTime := recurringsubscriptionMixinFields0[1].Descriptor()
	// recurringsubscription.DefaultUpdateTime holds the default value on creation for the update_time field.
	recurringsubscription.DefaultUpdateTime = recurringsubscriptionDescUpdateTime.Default.(func() time.Time)
	// recurringsubscription.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	recurringsubscription.UpdateDefaultUpdateTime = recurringsubscriptionDescUpdateTime.UpdateDefault.(func() time.Time)
	// recurringsubscriptionDescName is the schema descriptor for name field.
	recurringsubscriptionDescName := recurringsubscriptionFields[0].Descriptor()
	// recurringsubscription.NameValidator is a validator for the "name" field. It is called by the builders before save.
	recurringsubscription.NameValidator = recurringsubscriptionDescName.Validators[0].(func(string) error)
	// recurringsubscriptionDescIntervalCount is the schema descriptor for interval_count field.
	recurringsubscriptionDescIntervalCount := recurringsubscriptionFields[2].Descriptor()
	// recurringsubscription.DefaultIntervalCount holds the default value on creation for the interval_count field.
	recurringsubscription.DefaultIntervalCount = recurringsubscriptionDescIntervalCount.Default.(int)
	// recurringsubscription.IntervalCountValidator is a validator for the "interval_count" field. It is called by the builders before save.
	recurringsubscription.IntervalCountValidator = recurringsubscriptionDescIntervalCount.Validators[0].(func(int) error)
	// recurringsubscriptionDescActive is the schema descriptor for active field.
	recurringsubscriptionDescActive := recurringsubscriptionFields[4].Descriptor()
	// recurringsubscription.DefaultActive holds the default value on creation for the active field.
	recurringsubscription.DefaultActive = recurringsubscriptionDescActive.Default.(bool)
	// recurringsubscriptionDescCost is the schema descriptor for cost field.
	recurringsubscriptionDescCost := recurringsubscriptionFields[6].Descriptor()
	// recurringsubscription.DefaultCost holds the default value on creation for the cost field.
	recurringsubscription.DefaultCost = recurringsubscriptionDescCost.Default.(func() decimal.Decimal)
	// recurringsubscriptionDescCurrencyID is the schema descriptor for currency_id field.
	recurringsubscriptionDescCurrencyID := recurringsubscriptionFields[8].Descriptor()
	// recurringsubscription.CurrencyIDValidator is a validator for the "currency_id" field. It is called by the builders before save.
	recurringsubscription.CurrencyIDValidator = recurringsubscriptionDescCurrencyID.Validators[0].(func(int) error)
	// recurringsubscriptionDescUserID is the schema descriptor for user_id field.
	recurringsubscriptionDescUserID := recurringsubscriptionFields[9].Descriptor()
	// recurringsubscription.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	recurringsubscription.UserIDValidator = recurringsubscriptionDescUserID.Validators[0].(func(int) error)
	transactionMixin := schema.Transaction{}.Mixin()
	transaction.Policy = privacy.NewPolicies(transactionMixin[1], schema.Transaction{})
	transaction.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := transaction.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	transactionMixinFields0 := transactionMixin[0].Fields()
	_ = transactionMixinFields0
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescCreateTime is the schema descriptor for create_time field.
	transactionDescCreateTime := transactionMixinFields0[0].Descriptor()
	// transaction.DefaultCreateTime holds the default value on creation for the create_time field.
	transaction.DefaultCreateTime = transactionDescCreateTime.Default.(func() time.Time)
	// transactionDescUpdateTime is the schema descriptor for update_time field.
	transactionDescUpdateTime := transactionMixinFields0[1].Descriptor()
	// transaction.DefaultUpdateTime holds the default value on creation for the update_time field.
	transaction.DefaultUpdateTime = transactionDescUpdateTime.Default.(func() time.Time)
	// transaction.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	transaction.UpdateDefaultUpdateTime = transactionDescUpdateTime.UpdateDefault.(func() time.Time)
	// transactionDescUserID is the schema descriptor for user_id field.
	transactionDescUserID := transactionFields[2].Descriptor()
	// transaction.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	transaction.UserIDValidator = transactionDescUserID.Validators[0].(func(int) error)
	// transactionDescCategoryID is the schema descriptor for category_id field.
	transactionDescCategoryID := transactionFields[3].Descriptor()
	// transaction.CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	transaction.CategoryIDValidator = transactionDescCategoryID.Validators[0].(func(int) error)
	transactioncategoryMixin := schema.TransactionCategory{}.Mixin()
	transactioncategory.Policy = privacy.NewPolicies(transactioncategoryMixin[1], schema.TransactionCategory{})
	transactioncategory.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := transactioncategory.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	transactioncategoryMixinFields0 := transactioncategoryMixin[0].Fields()
	_ = transactioncategoryMixinFields0
	transactioncategoryFields := schema.TransactionCategory{}.Fields()
	_ = transactioncategoryFields
	// transactioncategoryDescCreateTime is the schema descriptor for create_time field.
	transactioncategoryDescCreateTime := transactioncategoryMixinFields0[0].Descriptor()
	// transactioncategory.DefaultCreateTime holds the default value on creation for the create_time field.
	transactioncategory.DefaultCreateTime = transactioncategoryDescCreateTime.Default.(func() time.Time)
	// transactioncategoryDescUpdateTime is the schema descriptor for update_time field.
	transactioncategoryDescUpdateTime := transactioncategoryMixinFields0[1].Descriptor()
	// transactioncategory.DefaultUpdateTime holds the default value on creation for the update_time field.
	transactioncategory.DefaultUpdateTime = transactioncategoryDescUpdateTime.Default.(func() time.Time)
	// transactioncategory.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	transactioncategory.UpdateDefaultUpdateTime = transactioncategoryDescUpdateTime.UpdateDefault.(func() time.Time)
	// transactioncategoryDescName is the schema descriptor for name field.
	transactioncategoryDescName := transactioncategoryFields[0].Descriptor()
	// transactioncategory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	transactioncategory.NameValidator = transactioncategoryDescName.Validators[0].(func(string) error)
	// transactioncategoryDescIsImmutable is the schema descriptor for is_immutable field.
	transactioncategoryDescIsImmutable := transactioncategoryFields[3].Descriptor()
	// transactioncategory.DefaultIsImmutable holds the default value on creation for the is_immutable field.
	transactioncategory.DefaultIsImmutable = transactioncategoryDescIsImmutable.Default.(bool)
	transactionentryMixin := schema.TransactionEntry{}.Mixin()
	transactionentry.Policy = privacy.NewPolicies(transactionentryMixin[1], schema.TransactionEntry{})
	transactionentry.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := transactionentry.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	transactionentryMixinFields0 := transactionentryMixin[0].Fields()
	_ = transactionentryMixinFields0
	transactionentryFields := schema.TransactionEntry{}.Fields()
	_ = transactionentryFields
	// transactionentryDescCreateTime is the schema descriptor for create_time field.
	transactionentryDescCreateTime := transactionentryMixinFields0[0].Descriptor()
	// transactionentry.DefaultCreateTime holds the default value on creation for the create_time field.
	transactionentry.DefaultCreateTime = transactionentryDescCreateTime.Default.(func() time.Time)
	// transactionentryDescUpdateTime is the schema descriptor for update_time field.
	transactionentryDescUpdateTime := transactionentryMixinFields0[1].Descriptor()
	// transactionentry.DefaultUpdateTime holds the default value on creation for the update_time field.
	transactionentry.DefaultUpdateTime = transactionentryDescUpdateTime.Default.(func() time.Time)
	// transactionentry.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	transactionentry.UpdateDefaultUpdateTime = transactionentryDescUpdateTime.UpdateDefault.(func() time.Time)
	// transactionentryDescAccountID is the schema descriptor for account_id field.
	transactionentryDescAccountID := transactionentryFields[1].Descriptor()
	// transactionentry.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	transactionentry.AccountIDValidator = transactionentryDescAccountID.Validators[0].(func(int) error)
	// transactionentryDescCurrencyID is the schema descriptor for currency_id field.
	transactionentryDescCurrencyID := transactionentryFields[2].Descriptor()
	// transactionentry.CurrencyIDValidator is a validator for the "currency_id" field. It is called by the builders before save.
	transactionentry.CurrencyIDValidator = transactionentryDescCurrencyID.Validators[0].(func(int) error)
	// transactionentryDescTransactionID is the schema descriptor for transaction_id field.
	transactionentryDescTransactionID := transactionentryFields[3].Descriptor()
	// transactionentry.TransactionIDValidator is a validator for the "transaction_id" field. It is called by the builders before save.
	transactionentry.TransactionIDValidator = transactionentryDescTransactionID.Validators[0].(func(int) error)
	userMixin := schema.User{}.Mixin()
	user.Policy = privacy.NewPolicies(schema.User{})
	user.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := user.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	userhouseholdMixin := schema.UserHousehold{}.Mixin()
	userhousehold.Policy = privacy.NewPolicies(schema.UserHousehold{})
	userhousehold.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := userhousehold.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	userhouseholdMixinFields0 := userhouseholdMixin[0].Fields()
	_ = userhouseholdMixinFields0
	userhouseholdFields := schema.UserHousehold{}.Fields()
	_ = userhouseholdFields
	// userhouseholdDescCreateTime is the schema descriptor for create_time field.
	userhouseholdDescCreateTime := userhouseholdMixinFields0[0].Descriptor()
	// userhousehold.DefaultCreateTime holds the default value on creation for the create_time field.
	userhousehold.DefaultCreateTime = userhouseholdDescCreateTime.Default.(func() time.Time)
	// userhouseholdDescUpdateTime is the schema descriptor for update_time field.
	userhouseholdDescUpdateTime := userhouseholdMixinFields0[1].Descriptor()
	// userhousehold.DefaultUpdateTime holds the default value on creation for the update_time field.
	userhousehold.DefaultUpdateTime = userhouseholdDescUpdateTime.Default.(func() time.Time)
	// userhousehold.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	userhousehold.UpdateDefaultUpdateTime = userhouseholdDescUpdateTime.UpdateDefault.(func() time.Time)
	userkeyMixin := schema.UserKey{}.Mixin()
	userkey.Policy = privacy.NewPolicies(schema.UserKey{})
	userkey.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := userkey.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	userkeyMixinFields0 := userkeyMixin[0].Fields()
	_ = userkeyMixinFields0
	userkeyFields := schema.UserKey{}.Fields()
	_ = userkeyFields
	// userkeyDescCreateTime is the schema descriptor for create_time field.
	userkeyDescCreateTime := userkeyMixinFields0[0].Descriptor()
	// userkey.DefaultCreateTime holds the default value on creation for the create_time field.
	userkey.DefaultCreateTime = userkeyDescCreateTime.Default.(func() time.Time)
	// userkeyDescUpdateTime is the schema descriptor for update_time field.
	userkeyDescUpdateTime := userkeyMixinFields0[1].Descriptor()
	// userkey.DefaultUpdateTime holds the default value on creation for the update_time field.
	userkey.DefaultUpdateTime = userkeyDescUpdateTime.Default.(func() time.Time)
	// userkey.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	userkey.UpdateDefaultUpdateTime = userkeyDescUpdateTime.UpdateDefault.(func() time.Time)
	// userkeyDescKey is the schema descriptor for key field.
	userkeyDescKey := userkeyFields[1].Descriptor()
	// userkey.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	userkey.KeyValidator = userkeyDescKey.Validators[0].(func(string) error)
	// userkeyDescUserID is the schema descriptor for user_id field.
	userkeyDescUserID := userkeyFields[2].Descriptor()
	// userkey.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userkey.UserIDValidator = userkeyDescUserID.Validators[0].(func(int) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
