type Mutation {
  createHousehold(input: CreateHouseholdInputCustom!): Household!
  updateHousehold(id: ID!, input: UpdateHouseholdInput!): Household!
  deleteHousehold(id: ID!): DeleteHouseholdPayload!

  createAccount(input: CreateAccountInput!): AccountEdge!
  updateAccount(id: ID!, input: UpdateAccountInput!): AccountEdge!
  deleteAccount(id: ID!): DeleteAccountPayload!
  archiveAccount(id: ID!): Boolean!
  unarchiveAccount(id: ID!): Account!

  createInvestment(input: CreateInvestmentInputCustom!): InvestmentEdge!

  createTransactionCategory(
    input: CreateTransactionCategoryInput!
  ): TransactionCategoryEdge!
  updateTransactionCategory(
    id: ID!
    input: UpdateTransactionCategoryInput!
  ): TransactionCategoryEdge!
  deleteTransactionCategory(id: ID!): DeleteTransactionCategoryPayload!

  createRecurringSubscription(
    input: CreateRecurringSubscriptionInput!
  ): RecurringSubscriptionEdge!
  updateRecurringSubscription(
    id: ID!
    input: UpdateRecurringSubscriptionInput!
  ): RecurringSubscriptionEdge!
  deleteRecurringSubscription(id: ID!): DeleteRecurringSubscriptionPayload!

  # Transaction mutations
  createExpense(input: CreateExpenseInputCustom!): TransactionEdge!
  createIncome(input: CreateIncomeInputCustom!): TransactionEdge!
  createTransfer(input: CreateTransferInputCustom!): TransactionEdge!
  buyInvestment(input: BuyInvestmentInputCustom!): TransactionEdge!
  sellInvestment(input: SellInvestmentInputCustom!): TransactionEdge!
  moveInvestment(input: MoveInvestmentInputCustom!): TransactionEdge!
  updateTransaction(id: ID!, input: UpdateTransactionInput!): TransactionEdge!
  updateTransactionEntry(id: ID!, input: UpdateTransactionEntryInput!): TransactionEntryEdge!
  updateInvestmentLot(id: ID!, input: UpdateInvestmentLotInput!): InvestmentLotEdge!
  deleteTransaction(id: ID!): DeleteTransactionPayload!

  createHouseholdCurrency(
    input: CreateHouseholdCurrencyInput!
  ): HouseholdCurrency!
  updateHouseholdCurrency(
    id: ID!
    input: UpdateHouseholdCurrencyInput!
  ): HouseholdCurrency!
  deleteHouseholdCurrency(id: ID!): DeleteHouseholdCurrencyPayload!

  addHouseholdUser(input: AddHouseholdUserInput!): UserHousehold!
  removeHouseholdUser(id: ID!): RemoveHouseholdUserPayload!
  updateHouseholdUserRole(id: ID!, role: UserHouseholdRole!): UserHousehold!

  createSnapshot(input: CreateSnapshotInput!): SnapshotEdge!
  updateSnapshot(id: ID!, input: UpdateSnapshotInput!): SnapshotEdge!
  deleteSnapshot(id: ID!): DeleteSnapshotPayload!

  refresh: Boolean!
}

type DeleteHouseholdPayload {
  deletedHouseholdId: ID!
}

type DeleteAccountPayload {
  deletedAccountId: ID!
}

type DeleteTransactionCategoryPayload {
  deletedTransactionCategoryId: ID!
}

type DeleteRecurringSubscriptionPayload {
  deletedRecurringSubscriptionId: ID!
}

type DeleteTransactionPayload {
  deletedTransactionId: ID!
}

type DeleteHouseholdCurrencyPayload {
  deletedHouseholdCurrencyId: ID!
}

type DeleteSnapshotPayload {
  deletedSnapshotId: ID!
}

input AddHouseholdUserInput {
  email: String!
  role: UserHouseholdRole!
  householdCurrencyID: ID!
}

type RemoveHouseholdUserPayload {
  removedUserHouseholdID: ID!
}

input CreateInvestmentInputCustom {
  input: CreateInvestmentInput!
  costBasis: String!
}

# Expense: Money out from account
input CreateExpenseInputCustom {
  transaction: CreateTransactionInput!
  transactionEntry: CreateTransactionEntryInput!
  fees: [CreateTransactionEntryInput!]! = []
}

# Income: Money in to account
input CreateIncomeInputCustom {
  transaction: CreateTransactionInput!
  transactionEntry: CreateTransactionEntryInput!
  fees: [CreateTransactionEntryInput!]! = []
}

# Transfer: Between two accounts
input CreateTransferInputCustom {
  transaction: CreateTransactionInput!
  # Should contain two entries: from and to
  transactionEntries: [CreateTransactionEntryInput!]!
  fees: [CreateTransactionEntryInput!]! = []
}

# Buy Investment: Cash -> Shares
input BuyInvestmentInputCustom {
  transaction: CreateTransactionInput!
  transactionEntry: CreateTransactionEntryInput!
  investmentLot: CreateInvestmentLotInput!
  fees: [CreateTransactionEntryInput!]! = []
}

# Sell Investment: Shares -> Cash
input SellInvestmentInputCustom {
  transaction: CreateTransactionInput!
  transactionEntry: CreateTransactionEntryInput!
  investmentLot: CreateInvestmentLotInput!
  fees: [CreateTransactionEntryInput!]! = []
}

# 6. Move Investment: Shares between investment accounts
input MoveInvestmentInputCustom {
  transaction: CreateTransactionInput!
  investmentLots: [CreateInvestmentLotInput!]!
  fees: [CreateTransactionEntryInput!]! = []
}

input CreateHouseholdInputCustom {
  input: CreateHouseholdInput!
  currencyCode: String!
}
