// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fijoy/ent/profile"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
)

// Profile is the model entity for the Profile schema.
type Profile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Locale holds the value of the "locale" field.
	Locale string `json:"locale,omitempty"`
	// Currencies holds the value of the "currencies" field.
	Currencies []string `json:"currencies,omitempty"`
	// NetWorthGoal holds the value of the "net_worth_goal" field.
	NetWorthGoal decimal.Decimal `json:"net_worth_goal,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProfileQuery when eager-loading is set.
	Edges        ProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProfileEdges holds the relations/edges for other nodes in the graph.
type ProfileEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// Transactions holds the value of the transactions edge.
	Transactions []*Transaction `json:"transactions,omitempty"`
	// Snapshots holds the value of the snapshots edge.
	Snapshots []*Snapshot `json:"snapshots,omitempty"`
	// UserProfiles holds the value of the user_profiles edge.
	UserProfiles []*UserProfile `json:"user_profiles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
	// totalCount holds the count of the edges above.
	totalCount [4]map[string]int

	namedUsers        map[string][]*User
	namedAccounts     map[string][]*Account
	namedTransactions map[string][]*Transaction
	namedSnapshots    map[string][]*Snapshot
	namedUserProfiles map[string][]*UserProfile
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[1] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) TransactionsOrErr() ([]*Transaction, error) {
	if e.loadedTypes[2] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// SnapshotsOrErr returns the Snapshots value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) SnapshotsOrErr() ([]*Snapshot, error) {
	if e.loadedTypes[3] {
		return e.Snapshots, nil
	}
	return nil, &NotLoadedError{edge: "snapshots"}
}

// UserProfilesOrErr returns the UserProfiles value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) UserProfilesOrErr() ([]*UserProfile, error) {
	if e.loadedTypes[4] {
		return e.UserProfiles, nil
	}
	return nil, &NotLoadedError{edge: "user_profiles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Profile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case profile.FieldCurrencies:
			values[i] = new([]byte)
		case profile.FieldNetWorthGoal:
			values[i] = new(decimal.Decimal)
		case profile.FieldID:
			values[i] = new(sql.NullInt64)
		case profile.FieldName, profile.FieldLocale:
			values[i] = new(sql.NullString)
		case profile.FieldCreateTime, profile.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Profile fields.
func (_m *Profile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case profile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case profile.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case profile.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case profile.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case profile.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case profile.FieldCurrencies:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field currencies", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Currencies); err != nil {
					return fmt.Errorf("unmarshal field currencies: %w", err)
				}
			}
		case profile.FieldNetWorthGoal:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field net_worth_goal", values[i])
			} else if value != nil {
				_m.NetWorthGoal = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Profile.
// This includes values selected through modifiers, order, etc.
func (_m *Profile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Profile entity.
func (_m *Profile) QueryUsers() *UserQuery {
	return NewProfileClient(_m.config).QueryUsers(_m)
}

// QueryAccounts queries the "accounts" edge of the Profile entity.
func (_m *Profile) QueryAccounts() *AccountQuery {
	return NewProfileClient(_m.config).QueryAccounts(_m)
}

// QueryTransactions queries the "transactions" edge of the Profile entity.
func (_m *Profile) QueryTransactions() *TransactionQuery {
	return NewProfileClient(_m.config).QueryTransactions(_m)
}

// QuerySnapshots queries the "snapshots" edge of the Profile entity.
func (_m *Profile) QuerySnapshots() *SnapshotQuery {
	return NewProfileClient(_m.config).QuerySnapshots(_m)
}

// QueryUserProfiles queries the "user_profiles" edge of the Profile entity.
func (_m *Profile) QueryUserProfiles() *UserProfileQuery {
	return NewProfileClient(_m.config).QueryUserProfiles(_m)
}

// Update returns a builder for updating this Profile.
// Note that you need to call Profile.Unwrap() before calling this method if this Profile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Profile) Update() *ProfileUpdateOne {
	return NewProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Profile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Profile) Unwrap() *Profile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Profile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Profile) String() string {
	var builder strings.Builder
	builder.WriteString("Profile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("currencies=")
	builder.WriteString(fmt.Sprintf("%v", _m.Currencies))
	builder.WriteString(", ")
	builder.WriteString("net_worth_goal=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetWorthGoal))
	builder.WriteByte(')')
	return builder.String()
}

// NamedUsers returns the Users named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Profile) NamedUsers(name string) ([]*User, error) {
	if _m.Edges.namedUsers == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedUsers[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Profile) appendNamedUsers(name string, edges ...*User) {
	if _m.Edges.namedUsers == nil {
		_m.Edges.namedUsers = make(map[string][]*User)
	}
	if len(edges) == 0 {
		_m.Edges.namedUsers[name] = []*User{}
	} else {
		_m.Edges.namedUsers[name] = append(_m.Edges.namedUsers[name], edges...)
	}
}

// NamedAccounts returns the Accounts named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Profile) NamedAccounts(name string) ([]*Account, error) {
	if _m.Edges.namedAccounts == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedAccounts[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Profile) appendNamedAccounts(name string, edges ...*Account) {
	if _m.Edges.namedAccounts == nil {
		_m.Edges.namedAccounts = make(map[string][]*Account)
	}
	if len(edges) == 0 {
		_m.Edges.namedAccounts[name] = []*Account{}
	} else {
		_m.Edges.namedAccounts[name] = append(_m.Edges.namedAccounts[name], edges...)
	}
}

// NamedTransactions returns the Transactions named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Profile) NamedTransactions(name string) ([]*Transaction, error) {
	if _m.Edges.namedTransactions == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedTransactions[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Profile) appendNamedTransactions(name string, edges ...*Transaction) {
	if _m.Edges.namedTransactions == nil {
		_m.Edges.namedTransactions = make(map[string][]*Transaction)
	}
	if len(edges) == 0 {
		_m.Edges.namedTransactions[name] = []*Transaction{}
	} else {
		_m.Edges.namedTransactions[name] = append(_m.Edges.namedTransactions[name], edges...)
	}
}

// NamedSnapshots returns the Snapshots named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Profile) NamedSnapshots(name string) ([]*Snapshot, error) {
	if _m.Edges.namedSnapshots == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedSnapshots[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Profile) appendNamedSnapshots(name string, edges ...*Snapshot) {
	if _m.Edges.namedSnapshots == nil {
		_m.Edges.namedSnapshots = make(map[string][]*Snapshot)
	}
	if len(edges) == 0 {
		_m.Edges.namedSnapshots[name] = []*Snapshot{}
	} else {
		_m.Edges.namedSnapshots[name] = append(_m.Edges.namedSnapshots[name], edges...)
	}
}

// NamedUserProfiles returns the UserProfiles named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Profile) NamedUserProfiles(name string) ([]*UserProfile, error) {
	if _m.Edges.namedUserProfiles == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedUserProfiles[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Profile) appendNamedUserProfiles(name string, edges ...*UserProfile) {
	if _m.Edges.namedUserProfiles == nil {
		_m.Edges.namedUserProfiles = make(map[string][]*UserProfile)
	}
	if len(edges) == 0 {
		_m.Edges.namedUserProfiles[name] = []*UserProfile{}
	} else {
		_m.Edges.namedUserProfiles[name] = append(_m.Edges.namedUserProfiles[name], edges...)
	}
}

// Profiles is a parsable slice of Profile.
type Profiles []*Profile
