// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fijoy/ent/account"
	"fijoy/ent/snapshot"
	"fijoy/ent/snapshotaccount"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
)

// SnapshotAccount is the model entity for the SnapshotAccount schema.
type SnapshotAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// The unit amount of share or money in this account
	Amount decimal.Decimal `json:"amount,omitempty"`
	// The value of 1 share in the native currency. If this is just a currency account, then this field will be 1
	Value decimal.Decimal `json:"value,omitempty"`
	// The total balance of this account its currency
	Balance decimal.Decimal `json:"balance,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SnapshotAccountQuery when eager-loading is set.
	Edges                      SnapshotAccountEdges `json:"edges"`
	account_snapshot_accounts  *int
	snapshot_snapshot_accounts *int
	selectValues               sql.SelectValues
}

// SnapshotAccountEdges holds the relations/edges for other nodes in the graph.
type SnapshotAccountEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Snapshot holds the value of the snapshot edge.
	Snapshot *Snapshot `json:"snapshot,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SnapshotAccountEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// SnapshotOrErr returns the Snapshot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SnapshotAccountEdges) SnapshotOrErr() (*Snapshot, error) {
	if e.Snapshot != nil {
		return e.Snapshot, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: snapshot.Label}
	}
	return nil, &NotLoadedError{edge: "snapshot"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SnapshotAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case snapshotaccount.FieldAmount, snapshotaccount.FieldValue, snapshotaccount.FieldBalance:
			values[i] = new(decimal.Decimal)
		case snapshotaccount.FieldID:
			values[i] = new(sql.NullInt64)
		case snapshotaccount.FieldCreateTime, snapshotaccount.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case snapshotaccount.ForeignKeys[0]: // account_snapshot_accounts
			values[i] = new(sql.NullInt64)
		case snapshotaccount.ForeignKeys[1]: // snapshot_snapshot_accounts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SnapshotAccount fields.
func (_m *SnapshotAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case snapshotaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case snapshotaccount.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case snapshotaccount.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case snapshotaccount.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				_m.Amount = *value
			}
		case snapshotaccount.FieldValue:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value != nil {
				_m.Value = *value
			}
		case snapshotaccount.FieldBalance:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value != nil {
				_m.Balance = *value
			}
		case snapshotaccount.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field account_snapshot_accounts", value)
			} else if value.Valid {
				_m.account_snapshot_accounts = new(int)
				*_m.account_snapshot_accounts = int(value.Int64)
			}
		case snapshotaccount.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field snapshot_snapshot_accounts", value)
			} else if value.Valid {
				_m.snapshot_snapshot_accounts = new(int)
				*_m.snapshot_snapshot_accounts = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the SnapshotAccount.
// This includes values selected through modifiers, order, etc.
func (_m *SnapshotAccount) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the SnapshotAccount entity.
func (_m *SnapshotAccount) QueryAccount() *AccountQuery {
	return NewSnapshotAccountClient(_m.config).QueryAccount(_m)
}

// QuerySnapshot queries the "snapshot" edge of the SnapshotAccount entity.
func (_m *SnapshotAccount) QuerySnapshot() *SnapshotQuery {
	return NewSnapshotAccountClient(_m.config).QuerySnapshot(_m)
}

// Update returns a builder for updating this SnapshotAccount.
// Note that you need to call SnapshotAccount.Unwrap() before calling this method if this SnapshotAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SnapshotAccount) Update() *SnapshotAccountUpdateOne {
	return NewSnapshotAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SnapshotAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SnapshotAccount) Unwrap() *SnapshotAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SnapshotAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SnapshotAccount) String() string {
	var builder strings.Builder
	builder.WriteString("SnapshotAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteByte(')')
	return builder.String()
}

// SnapshotAccounts is a parsable slice of SnapshotAccount.
type SnapshotAccounts []*SnapshotAccount
