// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"liquidity", "investment", "property", "receivable", "liability"}},
		{Name: "balance", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "icon_path", Type: field.TypeString, Nullable: true},
		{Name: "value", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "fx_rate", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "currency_accounts", Type: field.TypeInt},
		{Name: "household_id", Type: field.TypeInt},
		{Name: "user_accounts", Type: field.TypeInt},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_currencies_accounts",
				Columns:    []*schema.Column{AccountsColumns[9]},
				RefColumns: []*schema.Column{CurrenciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "accounts_households_accounts",
				Columns:    []*schema.Column{AccountsColumns[10]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "accounts_users_accounts",
				Columns:    []*schema.Column{AccountsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CurrenciesColumns holds the columns for the "currencies" table.
	CurrenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
	}
	// CurrenciesTable holds the schema information for the "currencies" table.
	CurrenciesTable = &schema.Table{
		Name:       "currencies",
		Columns:    CurrenciesColumns,
		PrimaryKey: []*schema.Column{CurrenciesColumns[0]},
	}
	// HouseholdsColumns holds the columns for the "households" table.
	HouseholdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "locale", Type: field.TypeString},
		{Name: "currency_households", Type: field.TypeInt},
	}
	// HouseholdsTable holds the schema information for the "households" table.
	HouseholdsTable = &schema.Table{
		Name:       "households",
		Columns:    HouseholdsColumns,
		PrimaryKey: []*schema.Column{HouseholdsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "households_currencies_households",
				Columns:    []*schema.Column{HouseholdsColumns[5]},
				RefColumns: []*schema.Column{CurrenciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// InvestmentsColumns holds the columns for the "investments" table.
	InvestmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"stock", "crypto"}},
		{Name: "symbol", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "quote", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "value", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "account_investments", Type: field.TypeInt},
		{Name: "currency_investments", Type: field.TypeInt},
		{Name: "household_id", Type: field.TypeInt},
	}
	// InvestmentsTable holds the schema information for the "investments" table.
	InvestmentsTable = &schema.Table{
		Name:       "investments",
		Columns:    InvestmentsColumns,
		PrimaryKey: []*schema.Column{InvestmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "investments_accounts_investments",
				Columns:    []*schema.Column{InvestmentsColumns[9]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "investments_currencies_investments",
				Columns:    []*schema.Column{InvestmentsColumns[10]},
				RefColumns: []*schema.Column{CurrenciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "investments_households_investments",
				Columns:    []*schema.Column{InvestmentsColumns[11]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LotsColumns holds the columns for the "lots" table.
	LotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "household_id", Type: field.TypeInt},
		{Name: "investment_lots", Type: field.TypeInt},
		{Name: "transaction_lots", Type: field.TypeInt},
	}
	// LotsTable holds the schema information for the "lots" table.
	LotsTable = &schema.Table{
		Name:       "lots",
		Columns:    LotsColumns,
		PrimaryKey: []*schema.Column{LotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lots_households_lots",
				Columns:    []*schema.Column{LotsColumns[5]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "lots_investments_lots",
				Columns:    []*schema.Column{LotsColumns[6]},
				RefColumns: []*schema.Column{InvestmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "lots_transactions_lots",
				Columns:    []*schema.Column{LotsColumns[7]},
				RefColumns: []*schema.Column{TransactionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "datetime", Type: field.TypeTime},
		{Name: "household_id", Type: field.TypeInt},
		{Name: "transaction_category_transactions", Type: field.TypeInt},
		{Name: "user_transactions", Type: field.TypeInt},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_households_transactions",
				Columns:    []*schema.Column{TransactionsColumns[5]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transactions_transaction_categories_transactions",
				Columns:    []*schema.Column{TransactionsColumns[6]},
				RefColumns: []*schema.Column{TransactionCategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transactions_users_transactions",
				Columns:    []*schema.Column{TransactionsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "transaction_datetime",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[4]},
			},
		},
	}
	// TransactionCategoriesColumns holds the columns for the "transaction_categories" table.
	TransactionCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"expense", "income", "transfer", "setup"}},
		{Name: "household_id", Type: field.TypeInt},
	}
	// TransactionCategoriesTable holds the schema information for the "transaction_categories" table.
	TransactionCategoriesTable = &schema.Table{
		Name:       "transaction_categories",
		Columns:    TransactionCategoriesColumns,
		PrimaryKey: []*schema.Column{TransactionCategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transaction_categories_households_transaction_categories",
				Columns:    []*schema.Column{TransactionCategoriesColumns[5]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TransactionEntriesColumns holds the columns for the "transaction_entries" table.
	TransactionEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(36,18)"}},
		{Name: "account_transaction_entries", Type: field.TypeInt},
		{Name: "currency_transaction_entries", Type: field.TypeInt},
		{Name: "household_id", Type: field.TypeInt},
		{Name: "transaction_transaction_entries", Type: field.TypeInt},
	}
	// TransactionEntriesTable holds the schema information for the "transaction_entries" table.
	TransactionEntriesTable = &schema.Table{
		Name:       "transaction_entries",
		Columns:    TransactionEntriesColumns,
		PrimaryKey: []*schema.Column{TransactionEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transaction_entries_accounts_transaction_entries",
				Columns:    []*schema.Column{TransactionEntriesColumns[4]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transaction_entries_currencies_transaction_entries",
				Columns:    []*schema.Column{TransactionEntriesColumns[5]},
				RefColumns: []*schema.Column{CurrenciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transaction_entries_households_transaction_entries",
				Columns:    []*schema.Column{TransactionEntriesColumns[6]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transaction_entries_transactions_transaction_entries",
				Columns:    []*schema.Column{TransactionEntriesColumns[7]},
				RefColumns: []*schema.Column{TransactionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserHouseholdsColumns holds the columns for the "user_households" table.
	UserHouseholdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member"}},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "household_id", Type: field.TypeInt},
	}
	// UserHouseholdsTable holds the schema information for the "user_households" table.
	UserHouseholdsTable = &schema.Table{
		Name:       "user_households",
		Columns:    UserHouseholdsColumns,
		PrimaryKey: []*schema.Column{UserHouseholdsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_households_users_user",
				Columns:    []*schema.Column{UserHouseholdsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_households_households_household",
				Columns:    []*schema.Column{UserHouseholdsColumns[5]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userhousehold_user_id_household_id",
				Unique:  true,
				Columns: []*schema.Column{UserHouseholdsColumns[4], UserHouseholdsColumns[5]},
			},
		},
	}
	// UserKeysColumns holds the columns for the "user_keys" table.
	UserKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"google"}},
		{Name: "key", Type: field.TypeString},
		{Name: "user_user_keys", Type: field.TypeInt},
	}
	// UserKeysTable holds the schema information for the "user_keys" table.
	UserKeysTable = &schema.Table{
		Name:       "user_keys",
		Columns:    UserKeysColumns,
		PrimaryKey: []*schema.Column{UserKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_keys_users_user_keys",
				Columns:    []*schema.Column{UserKeysColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userkey_provider_key",
				Unique:  true,
				Columns: []*schema.Column{UserKeysColumns[3], UserKeysColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		CurrenciesTable,
		HouseholdsTable,
		InvestmentsTable,
		LotsTable,
		TransactionsTable,
		TransactionCategoriesTable,
		TransactionEntriesTable,
		UsersTable,
		UserHouseholdsTable,
		UserKeysTable,
	}
)

func init() {
	AccountsTable.ForeignKeys[0].RefTable = CurrenciesTable
	AccountsTable.ForeignKeys[1].RefTable = HouseholdsTable
	AccountsTable.ForeignKeys[2].RefTable = UsersTable
	AccountsTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(0),
	}
	CurrenciesTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(4294967296),
	}
	HouseholdsTable.ForeignKeys[0].RefTable = CurrenciesTable
	HouseholdsTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(8589934592),
	}
	InvestmentsTable.ForeignKeys[0].RefTable = AccountsTable
	InvestmentsTable.ForeignKeys[1].RefTable = CurrenciesTable
	InvestmentsTable.ForeignKeys[2].RefTable = HouseholdsTable
	InvestmentsTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(30064771072),
	}
	LotsTable.ForeignKeys[0].RefTable = HouseholdsTable
	LotsTable.ForeignKeys[1].RefTable = InvestmentsTable
	LotsTable.ForeignKeys[2].RefTable = TransactionsTable
	LotsTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(34359738368),
	}
	TransactionsTable.ForeignKeys[0].RefTable = HouseholdsTable
	TransactionsTable.ForeignKeys[1].RefTable = TransactionCategoriesTable
	TransactionsTable.ForeignKeys[2].RefTable = UsersTable
	TransactionsTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(12884901888),
	}
	TransactionCategoriesTable.ForeignKeys[0].RefTable = HouseholdsTable
	TransactionCategoriesTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(38654705664),
	}
	TransactionEntriesTable.ForeignKeys[0].RefTable = AccountsTable
	TransactionEntriesTable.ForeignKeys[1].RefTable = CurrenciesTable
	TransactionEntriesTable.ForeignKeys[2].RefTable = HouseholdsTable
	TransactionEntriesTable.ForeignKeys[3].RefTable = TransactionsTable
	TransactionEntriesTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(17179869184),
	}
	UsersTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(21474836480),
	}
	UserHouseholdsTable.ForeignKeys[0].RefTable = UsersTable
	UserHouseholdsTable.ForeignKeys[1].RefTable = HouseholdsTable
	UserHouseholdsTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(25769803776),
	}
	UserKeysTable.ForeignKeys[0].RefTable = UsersTable
	UserKeysTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(42949672960),
	}
}
