//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type FijoyPayee struct {
	ID          string `sql:"primary_key" json:"ID"`
	Name        string `json:"Name"`
	WorkspaceID string `json:"WorkspaceID"`
}
