// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"beavermoney.app/ent/cryptoquotecache"
	"beavermoney.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CryptoQuoteCacheDelete is the builder for deleting a CryptoQuoteCache entity.
type CryptoQuoteCacheDelete struct {
	config
	hooks    []Hook
	mutation *CryptoQuoteCacheMutation
}

// Where appends a list predicates to the CryptoQuoteCacheDelete builder.
func (_d *CryptoQuoteCacheDelete) Where(ps ...predicate.CryptoQuoteCache) *CryptoQuoteCacheDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CryptoQuoteCacheDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CryptoQuoteCacheDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CryptoQuoteCacheDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cryptoquotecache.Table, sqlgraph.NewFieldSpec(cryptoquotecache.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CryptoQuoteCacheDeleteOne is the builder for deleting a single CryptoQuoteCache entity.
type CryptoQuoteCacheDeleteOne struct {
	_d *CryptoQuoteCacheDelete
}

// Where appends a list predicates to the CryptoQuoteCacheDelete builder.
func (_d *CryptoQuoteCacheDeleteOne) Where(ps ...predicate.CryptoQuoteCache) *CryptoQuoteCacheDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CryptoQuoteCacheDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cryptoquotecache.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CryptoQuoteCacheDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
