// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"beavermoney.app/ent/household"
	"beavermoney.app/ent/investment"
	"beavermoney.app/ent/investmentlot"
	"beavermoney.app/ent/transaction"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
)

// InvestmentLot is the model entity for the InvestmentLot schema.
type InvestmentLot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// HouseholdID holds the value of the "household_id" field.
	HouseholdID int `json:"household_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// Price holds the value of the "price" field.
	Price decimal.Decimal `json:"price,omitempty"`
	// InvestmentID holds the value of the "investment_id" field.
	InvestmentID int `json:"investment_id,omitempty"`
	// TransactionID holds the value of the "transaction_id" field.
	TransactionID int `json:"transaction_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvestmentLotQuery when eager-loading is set.
	Edges        InvestmentLotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvestmentLotEdges holds the relations/edges for other nodes in the graph.
type InvestmentLotEdges struct {
	// Household holds the value of the household edge.
	Household *Household `json:"household,omitempty"`
	// Investment holds the value of the investment edge.
	Investment *Investment `json:"investment,omitempty"`
	// Transaction holds the value of the transaction edge.
	Transaction *Transaction `json:"transaction,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int
}

// HouseholdOrErr returns the Household value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvestmentLotEdges) HouseholdOrErr() (*Household, error) {
	if e.Household != nil {
		return e.Household, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: household.Label}
	}
	return nil, &NotLoadedError{edge: "household"}
}

// InvestmentOrErr returns the Investment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvestmentLotEdges) InvestmentOrErr() (*Investment, error) {
	if e.Investment != nil {
		return e.Investment, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: investment.Label}
	}
	return nil, &NotLoadedError{edge: "investment"}
}

// TransactionOrErr returns the Transaction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvestmentLotEdges) TransactionOrErr() (*Transaction, error) {
	if e.Transaction != nil {
		return e.Transaction, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: transaction.Label}
	}
	return nil, &NotLoadedError{edge: "transaction"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvestmentLot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case investmentlot.FieldAmount, investmentlot.FieldPrice:
			values[i] = new(decimal.Decimal)
		case investmentlot.FieldID, investmentlot.FieldHouseholdID, investmentlot.FieldInvestmentID, investmentlot.FieldTransactionID:
			values[i] = new(sql.NullInt64)
		case investmentlot.FieldCreateTime, investmentlot.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvestmentLot fields.
func (_m *InvestmentLot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case investmentlot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case investmentlot.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case investmentlot.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case investmentlot.FieldHouseholdID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field household_id", values[i])
			} else if value.Valid {
				_m.HouseholdID = int(value.Int64)
			}
		case investmentlot.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				_m.Amount = *value
			}
		case investmentlot.FieldPrice:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value != nil {
				_m.Price = *value
			}
		case investmentlot.FieldInvestmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field investment_id", values[i])
			} else if value.Valid {
				_m.InvestmentID = int(value.Int64)
			}
		case investmentlot.FieldTransactionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_id", values[i])
			} else if value.Valid {
				_m.TransactionID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvestmentLot.
// This includes values selected through modifiers, order, etc.
func (_m *InvestmentLot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHousehold queries the "household" edge of the InvestmentLot entity.
func (_m *InvestmentLot) QueryHousehold() *HouseholdQuery {
	return NewInvestmentLotClient(_m.config).QueryHousehold(_m)
}

// QueryInvestment queries the "investment" edge of the InvestmentLot entity.
func (_m *InvestmentLot) QueryInvestment() *InvestmentQuery {
	return NewInvestmentLotClient(_m.config).QueryInvestment(_m)
}

// QueryTransaction queries the "transaction" edge of the InvestmentLot entity.
func (_m *InvestmentLot) QueryTransaction() *TransactionQuery {
	return NewInvestmentLotClient(_m.config).QueryTransaction(_m)
}

// Update returns a builder for updating this InvestmentLot.
// Note that you need to call InvestmentLot.Unwrap() before calling this method if this InvestmentLot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvestmentLot) Update() *InvestmentLotUpdateOne {
	return NewInvestmentLotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvestmentLot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvestmentLot) Unwrap() *InvestmentLot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvestmentLot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvestmentLot) String() string {
	var builder strings.Builder
	builder.WriteString("InvestmentLot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("household_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HouseholdID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("investment_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvestmentID))
	builder.WriteString(", ")
	builder.WriteString("transaction_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TransactionID))
	builder.WriteByte(')')
	return builder.String()
}

// InvestmentLots is a parsable slice of InvestmentLot.
type InvestmentLots []*InvestmentLot
