// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"beavermoney.app/ent/investment"
	"beavermoney.app/ent/investmentlot"
	"beavermoney.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
)

// InvestmentUpdate is the builder for updating Investment entities.
type InvestmentUpdate struct {
	config
	hooks     []Hook
	mutation  *InvestmentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the InvestmentUpdate builder.
func (_u *InvestmentUpdate) Where(ps ...predicate.Investment) *InvestmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *InvestmentUpdate) SetUpdateTime(v time.Time) *InvestmentUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *InvestmentUpdate) SetName(v string) *InvestmentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InvestmentUpdate) SetNillableName(v *string) *InvestmentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *InvestmentUpdate) SetType(v investment.Type) *InvestmentUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *InvestmentUpdate) SetNillableType(v *investment.Type) *InvestmentUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *InvestmentUpdate) SetSymbol(v string) *InvestmentUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *InvestmentUpdate) SetNillableSymbol(v *string) *InvestmentUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetQuote sets the "quote" field.
func (_u *InvestmentUpdate) SetQuote(v decimal.Decimal) *InvestmentUpdate {
	_u.mutation.ResetQuote()
	_u.mutation.SetQuote(v)
	return _u
}

// SetNillableQuote sets the "quote" field if the given value is not nil.
func (_u *InvestmentUpdate) SetNillableQuote(v *decimal.Decimal) *InvestmentUpdate {
	if v != nil {
		_u.SetQuote(*v)
	}
	return _u
}

// AddQuote adds value to the "quote" field.
func (_u *InvestmentUpdate) AddQuote(v decimal.Decimal) *InvestmentUpdate {
	_u.mutation.AddQuote(v)
	return _u
}

// AddInvestmentLotIDs adds the "investment_lots" edge to the InvestmentLot entity by IDs.
func (_u *InvestmentUpdate) AddInvestmentLotIDs(ids ...int) *InvestmentUpdate {
	_u.mutation.AddInvestmentLotIDs(ids...)
	return _u
}

// AddInvestmentLots adds the "investment_lots" edges to the InvestmentLot entity.
func (_u *InvestmentUpdate) AddInvestmentLots(v ...*InvestmentLot) *InvestmentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvestmentLotIDs(ids...)
}

// Mutation returns the InvestmentMutation object of the builder.
func (_u *InvestmentUpdate) Mutation() *InvestmentMutation {
	return _u.mutation
}

// ClearInvestmentLots clears all "investment_lots" edges to the InvestmentLot entity.
func (_u *InvestmentUpdate) ClearInvestmentLots() *InvestmentUpdate {
	_u.mutation.ClearInvestmentLots()
	return _u
}

// RemoveInvestmentLotIDs removes the "investment_lots" edge to InvestmentLot entities by IDs.
func (_u *InvestmentUpdate) RemoveInvestmentLotIDs(ids ...int) *InvestmentUpdate {
	_u.mutation.RemoveInvestmentLotIDs(ids...)
	return _u
}

// RemoveInvestmentLots removes "investment_lots" edges to InvestmentLot entities.
func (_u *InvestmentUpdate) RemoveInvestmentLots(v ...*InvestmentLot) *InvestmentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvestmentLotIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvestmentUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvestmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvestmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvestmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvestmentUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if investment.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized investment.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := investment.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvestmentUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := investment.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Investment.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := investment.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Investment.symbol": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Investment.account"`)
	}
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Investment.household"`)
	}
	if _u.mutation.CurrencyCleared() && len(_u.mutation.CurrencyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Investment.currency"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InvestmentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InvestmentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InvestmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(investment.Table, investment.Columns, sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(investment.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(investment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(investment.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(investment.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quote(); ok {
		_spec.SetField(investment.FieldQuote, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuote(); ok {
		_spec.AddField(investment.FieldQuote, field.TypeFloat64, value)
	}
	if _u.mutation.InvestmentLotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   investment.InvestmentLotsTable,
			Columns: []string{investment.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvestmentLotsIDs(); len(nodes) > 0 && !_u.mutation.InvestmentLotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   investment.InvestmentLotsTable,
			Columns: []string{investment.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvestmentLotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   investment.InvestmentLotsTable,
			Columns: []string{investment.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{investment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvestmentUpdateOne is the builder for updating a single Investment entity.
type InvestmentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *InvestmentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *InvestmentUpdateOne) SetUpdateTime(v time.Time) *InvestmentUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *InvestmentUpdateOne) SetName(v string) *InvestmentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InvestmentUpdateOne) SetNillableName(v *string) *InvestmentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *InvestmentUpdateOne) SetType(v investment.Type) *InvestmentUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *InvestmentUpdateOne) SetNillableType(v *investment.Type) *InvestmentUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *InvestmentUpdateOne) SetSymbol(v string) *InvestmentUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *InvestmentUpdateOne) SetNillableSymbol(v *string) *InvestmentUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetQuote sets the "quote" field.
func (_u *InvestmentUpdateOne) SetQuote(v decimal.Decimal) *InvestmentUpdateOne {
	_u.mutation.ResetQuote()
	_u.mutation.SetQuote(v)
	return _u
}

// SetNillableQuote sets the "quote" field if the given value is not nil.
func (_u *InvestmentUpdateOne) SetNillableQuote(v *decimal.Decimal) *InvestmentUpdateOne {
	if v != nil {
		_u.SetQuote(*v)
	}
	return _u
}

// AddQuote adds value to the "quote" field.
func (_u *InvestmentUpdateOne) AddQuote(v decimal.Decimal) *InvestmentUpdateOne {
	_u.mutation.AddQuote(v)
	return _u
}

// AddInvestmentLotIDs adds the "investment_lots" edge to the InvestmentLot entity by IDs.
func (_u *InvestmentUpdateOne) AddInvestmentLotIDs(ids ...int) *InvestmentUpdateOne {
	_u.mutation.AddInvestmentLotIDs(ids...)
	return _u
}

// AddInvestmentLots adds the "investment_lots" edges to the InvestmentLot entity.
func (_u *InvestmentUpdateOne) AddInvestmentLots(v ...*InvestmentLot) *InvestmentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvestmentLotIDs(ids...)
}

// Mutation returns the InvestmentMutation object of the builder.
func (_u *InvestmentUpdateOne) Mutation() *InvestmentMutation {
	return _u.mutation
}

// ClearInvestmentLots clears all "investment_lots" edges to the InvestmentLot entity.
func (_u *InvestmentUpdateOne) ClearInvestmentLots() *InvestmentUpdateOne {
	_u.mutation.ClearInvestmentLots()
	return _u
}

// RemoveInvestmentLotIDs removes the "investment_lots" edge to InvestmentLot entities by IDs.
func (_u *InvestmentUpdateOne) RemoveInvestmentLotIDs(ids ...int) *InvestmentUpdateOne {
	_u.mutation.RemoveInvestmentLotIDs(ids...)
	return _u
}

// RemoveInvestmentLots removes "investment_lots" edges to InvestmentLot entities.
func (_u *InvestmentUpdateOne) RemoveInvestmentLots(v ...*InvestmentLot) *InvestmentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvestmentLotIDs(ids...)
}

// Where appends a list predicates to the InvestmentUpdate builder.
func (_u *InvestmentUpdateOne) Where(ps ...predicate.Investment) *InvestmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvestmentUpdateOne) Select(field string, fields ...string) *InvestmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Investment entity.
func (_u *InvestmentUpdateOne) Save(ctx context.Context) (*Investment, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvestmentUpdateOne) SaveX(ctx context.Context) *Investment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvestmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvestmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvestmentUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if investment.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized investment.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := investment.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvestmentUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := investment.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Investment.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := investment.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Investment.symbol": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Investment.account"`)
	}
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Investment.household"`)
	}
	if _u.mutation.CurrencyCleared() && len(_u.mutation.CurrencyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Investment.currency"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InvestmentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InvestmentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InvestmentUpdateOne) sqlSave(ctx context.Context) (_node *Investment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(investment.Table, investment.Columns, sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Investment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, investment.FieldID)
		for _, f := range fields {
			if !investment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != investment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(investment.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(investment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(investment.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(investment.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quote(); ok {
		_spec.SetField(investment.FieldQuote, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuote(); ok {
		_spec.AddField(investment.FieldQuote, field.TypeFloat64, value)
	}
	if _u.mutation.InvestmentLotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   investment.InvestmentLotsTable,
			Columns: []string{investment.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvestmentLotsIDs(); len(nodes) > 0 && !_u.mutation.InvestmentLotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   investment.InvestmentLotsTable,
			Columns: []string{investment.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvestmentLotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   investment.InvestmentLotsTable,
			Columns: []string{investment.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Investment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{investment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
