// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"beavermoney.app/ent/currency"
	"beavermoney.app/ent/household"
	"beavermoney.app/ent/recurringsubscription"
	"beavermoney.app/ent/user"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
)

// RecurringSubscriptionCreate is the builder for creating a RecurringSubscription entity.
type RecurringSubscriptionCreate struct {
	config
	mutation *RecurringSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *RecurringSubscriptionCreate) SetCreateTime(v time.Time) *RecurringSubscriptionCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *RecurringSubscriptionCreate) SetNillableCreateTime(v *time.Time) *RecurringSubscriptionCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *RecurringSubscriptionCreate) SetUpdateTime(v time.Time) *RecurringSubscriptionCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *RecurringSubscriptionCreate) SetNillableUpdateTime(v *time.Time) *RecurringSubscriptionCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetHouseholdID sets the "household_id" field.
func (_c *RecurringSubscriptionCreate) SetHouseholdID(v int) *RecurringSubscriptionCreate {
	_c.mutation.SetHouseholdID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RecurringSubscriptionCreate) SetName(v string) *RecurringSubscriptionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetInterval sets the "interval" field.
func (_c *RecurringSubscriptionCreate) SetInterval(v recurringsubscription.Interval) *RecurringSubscriptionCreate {
	_c.mutation.SetInterval(v)
	return _c
}

// SetIntervalCount sets the "interval_count" field.
func (_c *RecurringSubscriptionCreate) SetIntervalCount(v int) *RecurringSubscriptionCreate {
	_c.mutation.SetIntervalCount(v)
	return _c
}

// SetNillableIntervalCount sets the "interval_count" field if the given value is not nil.
func (_c *RecurringSubscriptionCreate) SetNillableIntervalCount(v *int) *RecurringSubscriptionCreate {
	if v != nil {
		_c.SetIntervalCount(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *RecurringSubscriptionCreate) SetStartDate(v time.Time) *RecurringSubscriptionCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *RecurringSubscriptionCreate) SetActive(v bool) *RecurringSubscriptionCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *RecurringSubscriptionCreate) SetNillableActive(v *bool) *RecurringSubscriptionCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *RecurringSubscriptionCreate) SetIcon(v string) *RecurringSubscriptionCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *RecurringSubscriptionCreate) SetNillableIcon(v *string) *RecurringSubscriptionCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *RecurringSubscriptionCreate) SetCost(v decimal.Decimal) *RecurringSubscriptionCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *RecurringSubscriptionCreate) SetNillableCost(v *decimal.Decimal) *RecurringSubscriptionCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetFxRate sets the "fx_rate" field.
func (_c *RecurringSubscriptionCreate) SetFxRate(v decimal.Decimal) *RecurringSubscriptionCreate {
	_c.mutation.SetFxRate(v)
	return _c
}

// SetCurrencyID sets the "currency_id" field.
func (_c *RecurringSubscriptionCreate) SetCurrencyID(v int) *RecurringSubscriptionCreate {
	_c.mutation.SetCurrencyID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RecurringSubscriptionCreate) SetUserID(v int) *RecurringSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetHousehold sets the "household" edge to the Household entity.
func (_c *RecurringSubscriptionCreate) SetHousehold(v *Household) *RecurringSubscriptionCreate {
	return _c.SetHouseholdID(v.ID)
}

// SetCurrency sets the "currency" edge to the Currency entity.
func (_c *RecurringSubscriptionCreate) SetCurrency(v *Currency) *RecurringSubscriptionCreate {
	return _c.SetCurrencyID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *RecurringSubscriptionCreate) SetUser(v *User) *RecurringSubscriptionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the RecurringSubscriptionMutation object of the builder.
func (_c *RecurringSubscriptionCreate) Mutation() *RecurringSubscriptionMutation {
	return _c.mutation
}

// Save creates the RecurringSubscription in the database.
func (_c *RecurringSubscriptionCreate) Save(ctx context.Context) (*RecurringSubscription, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecurringSubscriptionCreate) SaveX(ctx context.Context) *RecurringSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecurringSubscriptionCreate) defaults() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		if recurringsubscription.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized recurringsubscription.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := recurringsubscription.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		if recurringsubscription.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized recurringsubscription.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := recurringsubscription.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IntervalCount(); !ok {
		v := recurringsubscription.DefaultIntervalCount
		_c.mutation.SetIntervalCount(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := recurringsubscription.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		if recurringsubscription.DefaultCost == nil {
			return fmt.Errorf("ent: uninitialized recurringsubscription.DefaultCost (forgotten import ent/runtime?)")
		}
		v := recurringsubscription.DefaultCost()
		_c.mutation.SetCost(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecurringSubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "RecurringSubscription.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "RecurringSubscription.update_time"`)}
	}
	if _, ok := _c.mutation.HouseholdID(); !ok {
		return &ValidationError{Name: "household_id", err: errors.New(`ent: missing required field "RecurringSubscription.household_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RecurringSubscription.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := recurringsubscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RecurringSubscription.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Interval(); !ok {
		return &ValidationError{Name: "interval", err: errors.New(`ent: missing required field "RecurringSubscription.interval"`)}
	}
	if v, ok := _c.mutation.Interval(); ok {
		if err := recurringsubscription.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "RecurringSubscription.interval": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntervalCount(); !ok {
		return &ValidationError{Name: "interval_count", err: errors.New(`ent: missing required field "RecurringSubscription.interval_count"`)}
	}
	if v, ok := _c.mutation.IntervalCount(); ok {
		if err := recurringsubscription.IntervalCountValidator(v); err != nil {
			return &ValidationError{Name: "interval_count", err: fmt.Errorf(`ent: validator failed for field "RecurringSubscription.interval_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "RecurringSubscription.start_date"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "RecurringSubscription.active"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "RecurringSubscription.cost"`)}
	}
	if _, ok := _c.mutation.FxRate(); !ok {
		return &ValidationError{Name: "fx_rate", err: errors.New(`ent: missing required field "RecurringSubscription.fx_rate"`)}
	}
	if _, ok := _c.mutation.CurrencyID(); !ok {
		return &ValidationError{Name: "currency_id", err: errors.New(`ent: missing required field "RecurringSubscription.currency_id"`)}
	}
	if v, ok := _c.mutation.CurrencyID(); ok {
		if err := recurringsubscription.CurrencyIDValidator(v); err != nil {
			return &ValidationError{Name: "currency_id", err: fmt.Errorf(`ent: validator failed for field "RecurringSubscription.currency_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RecurringSubscription.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := recurringsubscription.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RecurringSubscription.user_id": %w`, err)}
		}
	}
	if len(_c.mutation.HouseholdIDs()) == 0 {
		return &ValidationError{Name: "household", err: errors.New(`ent: missing required edge "RecurringSubscription.household"`)}
	}
	if len(_c.mutation.CurrencyIDs()) == 0 {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required edge "RecurringSubscription.currency"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RecurringSubscription.user"`)}
	}
	return nil
}

func (_c *RecurringSubscriptionCreate) sqlSave(ctx context.Context) (*RecurringSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecurringSubscriptionCreate) createSpec() (*RecurringSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &RecurringSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recurringsubscription.Table, sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(recurringsubscription.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(recurringsubscription.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(recurringsubscription.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Interval(); ok {
		_spec.SetField(recurringsubscription.FieldInterval, field.TypeEnum, value)
		_node.Interval = value
	}
	if value, ok := _c.mutation.IntervalCount(); ok {
		_spec.SetField(recurringsubscription.FieldIntervalCount, field.TypeInt, value)
		_node.IntervalCount = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(recurringsubscription.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(recurringsubscription.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(recurringsubscription.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(recurringsubscription.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.FxRate(); ok {
		_spec.SetField(recurringsubscription.FieldFxRate, field.TypeFloat64, value)
		_node.FxRate = value
	}
	if nodes := _c.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringsubscription.HouseholdTable,
			Columns: []string{recurringsubscription.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HouseholdID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringsubscription.CurrencyTable,
			Columns: []string{recurringsubscription.CurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CurrencyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringsubscription.UserTable,
			Columns: []string{recurringsubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RecurringSubscription.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecurringSubscriptionUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *RecurringSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *RecurringSubscriptionUpsertOne {
	_c.conflict = opts
	return &RecurringSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RecurringSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RecurringSubscriptionCreate) OnConflictColumns(columns ...string) *RecurringSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RecurringSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// RecurringSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one RecurringSubscription node.
	RecurringSubscriptionUpsertOne struct {
		create *RecurringSubscriptionCreate
	}

	// RecurringSubscriptionUpsert is the "OnConflict" setter.
	RecurringSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *RecurringSubscriptionUpsert) SetUpdateTime(v time.Time) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateUpdateTime() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldUpdateTime)
	return u
}

// SetName sets the "name" field.
func (u *RecurringSubscriptionUpsert) SetName(v string) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateName() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldName)
	return u
}

// SetInterval sets the "interval" field.
func (u *RecurringSubscriptionUpsert) SetInterval(v recurringsubscription.Interval) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldInterval, v)
	return u
}

// UpdateInterval sets the "interval" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateInterval() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldInterval)
	return u
}

// SetIntervalCount sets the "interval_count" field.
func (u *RecurringSubscriptionUpsert) SetIntervalCount(v int) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldIntervalCount, v)
	return u
}

// UpdateIntervalCount sets the "interval_count" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateIntervalCount() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldIntervalCount)
	return u
}

// AddIntervalCount adds v to the "interval_count" field.
func (u *RecurringSubscriptionUpsert) AddIntervalCount(v int) *RecurringSubscriptionUpsert {
	u.Add(recurringsubscription.FieldIntervalCount, v)
	return u
}

// SetStartDate sets the "start_date" field.
func (u *RecurringSubscriptionUpsert) SetStartDate(v time.Time) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldStartDate, v)
	return u
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateStartDate() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldStartDate)
	return u
}

// SetActive sets the "active" field.
func (u *RecurringSubscriptionUpsert) SetActive(v bool) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateActive() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldActive)
	return u
}

// SetIcon sets the "icon" field.
func (u *RecurringSubscriptionUpsert) SetIcon(v string) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateIcon() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldIcon)
	return u
}

// ClearIcon clears the value of the "icon" field.
func (u *RecurringSubscriptionUpsert) ClearIcon() *RecurringSubscriptionUpsert {
	u.SetNull(recurringsubscription.FieldIcon)
	return u
}

// SetCost sets the "cost" field.
func (u *RecurringSubscriptionUpsert) SetCost(v decimal.Decimal) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateCost() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *RecurringSubscriptionUpsert) AddCost(v decimal.Decimal) *RecurringSubscriptionUpsert {
	u.Add(recurringsubscription.FieldCost, v)
	return u
}

// SetFxRate sets the "fx_rate" field.
func (u *RecurringSubscriptionUpsert) SetFxRate(v decimal.Decimal) *RecurringSubscriptionUpsert {
	u.Set(recurringsubscription.FieldFxRate, v)
	return u
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsert) UpdateFxRate() *RecurringSubscriptionUpsert {
	u.SetExcluded(recurringsubscription.FieldFxRate)
	return u
}

// AddFxRate adds v to the "fx_rate" field.
func (u *RecurringSubscriptionUpsert) AddFxRate(v decimal.Decimal) *RecurringSubscriptionUpsert {
	u.Add(recurringsubscription.FieldFxRate, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RecurringSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RecurringSubscriptionUpsertOne) UpdateNewValues() *RecurringSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(recurringsubscription.FieldCreateTime)
		}
		if _, exists := u.create.mutation.HouseholdID(); exists {
			s.SetIgnore(recurringsubscription.FieldHouseholdID)
		}
		if _, exists := u.create.mutation.CurrencyID(); exists {
			s.SetIgnore(recurringsubscription.FieldCurrencyID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(recurringsubscription.FieldUserID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RecurringSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RecurringSubscriptionUpsertOne) Ignore() *RecurringSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecurringSubscriptionUpsertOne) DoNothing() *RecurringSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecurringSubscriptionCreate.OnConflict
// documentation for more info.
func (u *RecurringSubscriptionUpsertOne) Update(set func(*RecurringSubscriptionUpsert)) *RecurringSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecurringSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *RecurringSubscriptionUpsertOne) SetUpdateTime(v time.Time) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateUpdateTime() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetName sets the "name" field.
func (u *RecurringSubscriptionUpsertOne) SetName(v string) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateName() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateName()
	})
}

// SetInterval sets the "interval" field.
func (u *RecurringSubscriptionUpsertOne) SetInterval(v recurringsubscription.Interval) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetInterval(v)
	})
}

// UpdateInterval sets the "interval" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateInterval() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateInterval()
	})
}

// SetIntervalCount sets the "interval_count" field.
func (u *RecurringSubscriptionUpsertOne) SetIntervalCount(v int) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetIntervalCount(v)
	})
}

// AddIntervalCount adds v to the "interval_count" field.
func (u *RecurringSubscriptionUpsertOne) AddIntervalCount(v int) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.AddIntervalCount(v)
	})
}

// UpdateIntervalCount sets the "interval_count" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateIntervalCount() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateIntervalCount()
	})
}

// SetStartDate sets the "start_date" field.
func (u *RecurringSubscriptionUpsertOne) SetStartDate(v time.Time) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateStartDate() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateStartDate()
	})
}

// SetActive sets the "active" field.
func (u *RecurringSubscriptionUpsertOne) SetActive(v bool) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateActive() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateActive()
	})
}

// SetIcon sets the "icon" field.
func (u *RecurringSubscriptionUpsertOne) SetIcon(v string) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateIcon() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateIcon()
	})
}

// ClearIcon clears the value of the "icon" field.
func (u *RecurringSubscriptionUpsertOne) ClearIcon() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.ClearIcon()
	})
}

// SetCost sets the "cost" field.
func (u *RecurringSubscriptionUpsertOne) SetCost(v decimal.Decimal) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *RecurringSubscriptionUpsertOne) AddCost(v decimal.Decimal) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateCost() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateCost()
	})
}

// SetFxRate sets the "fx_rate" field.
func (u *RecurringSubscriptionUpsertOne) SetFxRate(v decimal.Decimal) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetFxRate(v)
	})
}

// AddFxRate adds v to the "fx_rate" field.
func (u *RecurringSubscriptionUpsertOne) AddFxRate(v decimal.Decimal) *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.AddFxRate(v)
	})
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertOne) UpdateFxRate() *RecurringSubscriptionUpsertOne {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateFxRate()
	})
}

// Exec executes the query.
func (u *RecurringSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecurringSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecurringSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RecurringSubscriptionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RecurringSubscriptionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RecurringSubscriptionCreateBulk is the builder for creating many RecurringSubscription entities in bulk.
type RecurringSubscriptionCreateBulk struct {
	config
	err      error
	builders []*RecurringSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the RecurringSubscription entities in the database.
func (_c *RecurringSubscriptionCreateBulk) Save(ctx context.Context) ([]*RecurringSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecurringSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecurringSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecurringSubscriptionCreateBulk) SaveX(ctx context.Context) []*RecurringSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RecurringSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecurringSubscriptionUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *RecurringSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RecurringSubscriptionUpsertBulk {
	_c.conflict = opts
	return &RecurringSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RecurringSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RecurringSubscriptionCreateBulk) OnConflictColumns(columns ...string) *RecurringSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RecurringSubscriptionUpsertBulk{
		create: _c,
	}
}

// RecurringSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of RecurringSubscription nodes.
type RecurringSubscriptionUpsertBulk struct {
	create *RecurringSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RecurringSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RecurringSubscriptionUpsertBulk) UpdateNewValues() *RecurringSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(recurringsubscription.FieldCreateTime)
			}
			if _, exists := b.mutation.HouseholdID(); exists {
				s.SetIgnore(recurringsubscription.FieldHouseholdID)
			}
			if _, exists := b.mutation.CurrencyID(); exists {
				s.SetIgnore(recurringsubscription.FieldCurrencyID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(recurringsubscription.FieldUserID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RecurringSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RecurringSubscriptionUpsertBulk) Ignore() *RecurringSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecurringSubscriptionUpsertBulk) DoNothing() *RecurringSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecurringSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *RecurringSubscriptionUpsertBulk) Update(set func(*RecurringSubscriptionUpsert)) *RecurringSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecurringSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *RecurringSubscriptionUpsertBulk) SetUpdateTime(v time.Time) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateUpdateTime() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetName sets the "name" field.
func (u *RecurringSubscriptionUpsertBulk) SetName(v string) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateName() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateName()
	})
}

// SetInterval sets the "interval" field.
func (u *RecurringSubscriptionUpsertBulk) SetInterval(v recurringsubscription.Interval) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetInterval(v)
	})
}

// UpdateInterval sets the "interval" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateInterval() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateInterval()
	})
}

// SetIntervalCount sets the "interval_count" field.
func (u *RecurringSubscriptionUpsertBulk) SetIntervalCount(v int) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetIntervalCount(v)
	})
}

// AddIntervalCount adds v to the "interval_count" field.
func (u *RecurringSubscriptionUpsertBulk) AddIntervalCount(v int) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.AddIntervalCount(v)
	})
}

// UpdateIntervalCount sets the "interval_count" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateIntervalCount() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateIntervalCount()
	})
}

// SetStartDate sets the "start_date" field.
func (u *RecurringSubscriptionUpsertBulk) SetStartDate(v time.Time) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateStartDate() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateStartDate()
	})
}

// SetActive sets the "active" field.
func (u *RecurringSubscriptionUpsertBulk) SetActive(v bool) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateActive() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateActive()
	})
}

// SetIcon sets the "icon" field.
func (u *RecurringSubscriptionUpsertBulk) SetIcon(v string) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateIcon() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateIcon()
	})
}

// ClearIcon clears the value of the "icon" field.
func (u *RecurringSubscriptionUpsertBulk) ClearIcon() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.ClearIcon()
	})
}

// SetCost sets the "cost" field.
func (u *RecurringSubscriptionUpsertBulk) SetCost(v decimal.Decimal) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *RecurringSubscriptionUpsertBulk) AddCost(v decimal.Decimal) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateCost() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateCost()
	})
}

// SetFxRate sets the "fx_rate" field.
func (u *RecurringSubscriptionUpsertBulk) SetFxRate(v decimal.Decimal) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.SetFxRate(v)
	})
}

// AddFxRate adds v to the "fx_rate" field.
func (u *RecurringSubscriptionUpsertBulk) AddFxRate(v decimal.Decimal) *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.AddFxRate(v)
	})
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *RecurringSubscriptionUpsertBulk) UpdateFxRate() *RecurringSubscriptionUpsertBulk {
	return u.Update(func(s *RecurringSubscriptionUpsert) {
		s.UpdateFxRate()
	})
}

// Exec executes the query.
func (u *RecurringSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RecurringSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecurringSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecurringSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
