// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"fijoy.app/ent/household"
	"fijoy.app/ent/lot"
	"fijoy.app/ent/predicate"
	"fijoy.app/ent/transaction"
	"fijoy.app/ent/transactioncategory"
	"fijoy.app/ent/transactionentry"
	"fijoy.app/ent/user"
)

// TransactionQuery is the builder for querying Transaction entities.
type TransactionQuery struct {
	config
	ctx                         *QueryContext
	order                       []transaction.OrderOption
	inters                      []Interceptor
	predicates                  []predicate.Transaction
	withUser                    *UserQuery
	withHousehold               *HouseholdQuery
	withCategory                *TransactionCategoryQuery
	withTransactionEntries      *TransactionEntryQuery
	withLots                    *LotQuery
	withFKs                     bool
	loadTotal                   []func(context.Context, []*Transaction) error
	modifiers                   []func(*sql.Selector)
	withNamedTransactionEntries map[string]*TransactionEntryQuery
	withNamedLots               map[string]*LotQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TransactionQuery builder.
func (_q *TransactionQuery) Where(ps ...predicate.Transaction) *TransactionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TransactionQuery) Limit(limit int) *TransactionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TransactionQuery) Offset(offset int) *TransactionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TransactionQuery) Unique(unique bool) *TransactionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TransactionQuery) Order(o ...transaction.OrderOption) *TransactionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *TransactionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transaction.Table, transaction.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, transaction.UserTable, transaction.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHousehold chains the current query on the "household" edge.
func (_q *TransactionQuery) QueryHousehold() *HouseholdQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transaction.Table, transaction.FieldID, selector),
			sqlgraph.To(household.Table, household.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, transaction.HouseholdTable, transaction.HouseholdColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategory chains the current query on the "category" edge.
func (_q *TransactionQuery) QueryCategory() *TransactionCategoryQuery {
	query := (&TransactionCategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transaction.Table, transaction.FieldID, selector),
			sqlgraph.To(transactioncategory.Table, transactioncategory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, transaction.CategoryTable, transaction.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTransactionEntries chains the current query on the "transaction_entries" edge.
func (_q *TransactionQuery) QueryTransactionEntries() *TransactionEntryQuery {
	query := (&TransactionEntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transaction.Table, transaction.FieldID, selector),
			sqlgraph.To(transactionentry.Table, transactionentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, transaction.TransactionEntriesTable, transaction.TransactionEntriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLots chains the current query on the "lots" edge.
func (_q *TransactionQuery) QueryLots() *LotQuery {
	query := (&LotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transaction.Table, transaction.FieldID, selector),
			sqlgraph.To(lot.Table, lot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, transaction.LotsTable, transaction.LotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Transaction entity from the query.
// Returns a *NotFoundError when no Transaction was found.
func (_q *TransactionQuery) First(ctx context.Context) (*Transaction, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{transaction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TransactionQuery) FirstX(ctx context.Context) *Transaction {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Transaction ID from the query.
// Returns a *NotFoundError when no Transaction ID was found.
func (_q *TransactionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{transaction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TransactionQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Transaction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Transaction entity is found.
// Returns a *NotFoundError when no Transaction entities are found.
func (_q *TransactionQuery) Only(ctx context.Context) (*Transaction, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{transaction.Label}
	default:
		return nil, &NotSingularError{transaction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TransactionQuery) OnlyX(ctx context.Context) *Transaction {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Transaction ID in the query.
// Returns a *NotSingularError when more than one Transaction ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TransactionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{transaction.Label}
	default:
		err = &NotSingularError{transaction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TransactionQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Transactions.
func (_q *TransactionQuery) All(ctx context.Context) ([]*Transaction, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Transaction, *TransactionQuery]()
	return withInterceptors[[]*Transaction](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TransactionQuery) AllX(ctx context.Context) []*Transaction {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Transaction IDs.
func (_q *TransactionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(transaction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TransactionQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TransactionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TransactionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TransactionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TransactionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TransactionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TransactionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TransactionQuery) Clone() *TransactionQuery {
	if _q == nil {
		return nil
	}
	return &TransactionQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]transaction.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.Transaction{}, _q.predicates...),
		withUser:               _q.withUser.Clone(),
		withHousehold:          _q.withHousehold.Clone(),
		withCategory:           _q.withCategory.Clone(),
		withTransactionEntries: _q.withTransactionEntries.Clone(),
		withLots:               _q.withLots.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionQuery) WithUser(opts ...func(*UserQuery)) *TransactionQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithHousehold tells the query-builder to eager-load the nodes that are connected to
// the "household" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionQuery) WithHousehold(opts ...func(*HouseholdQuery)) *TransactionQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHousehold = query
	return _q
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionQuery) WithCategory(opts ...func(*TransactionCategoryQuery)) *TransactionQuery {
	query := (&TransactionCategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategory = query
	return _q
}

// WithTransactionEntries tells the query-builder to eager-load the nodes that are connected to
// the "transaction_entries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionQuery) WithTransactionEntries(opts ...func(*TransactionEntryQuery)) *TransactionQuery {
	query := (&TransactionEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTransactionEntries = query
	return _q
}

// WithLots tells the query-builder to eager-load the nodes that are connected to
// the "lots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionQuery) WithLots(opts ...func(*LotQuery)) *TransactionQuery {
	query := (&LotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLots = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Transaction.Query().
//		GroupBy(transaction.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TransactionQuery) GroupBy(field string, fields ...string) *TransactionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TransactionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = transaction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Transaction.Query().
//		Select(transaction.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *TransactionQuery) Select(fields ...string) *TransactionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TransactionSelect{TransactionQuery: _q}
	sbuild.label = transaction.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TransactionSelect configured with the given aggregations.
func (_q *TransactionQuery) Aggregate(fns ...AggregateFunc) *TransactionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TransactionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !transaction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if transaction.Policy == nil {
		return errors.New("ent: uninitialized transaction.Policy (forgotten import ent/runtime?)")
	}
	if err := transaction.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *TransactionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Transaction, error) {
	var (
		nodes       = []*Transaction{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withUser != nil,
			_q.withHousehold != nil,
			_q.withCategory != nil,
			_q.withTransactionEntries != nil,
			_q.withLots != nil,
		}
	)
	if _q.withUser != nil || _q.withCategory != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Transaction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Transaction{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *Transaction, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withHousehold; query != nil {
		if err := _q.loadHousehold(ctx, query, nodes, nil,
			func(n *Transaction, e *Household) { n.Edges.Household = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCategory; query != nil {
		if err := _q.loadCategory(ctx, query, nodes, nil,
			func(n *Transaction, e *TransactionCategory) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTransactionEntries; query != nil {
		if err := _q.loadTransactionEntries(ctx, query, nodes,
			func(n *Transaction) { n.Edges.TransactionEntries = []*TransactionEntry{} },
			func(n *Transaction, e *TransactionEntry) {
				n.Edges.TransactionEntries = append(n.Edges.TransactionEntries, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withLots; query != nil {
		if err := _q.loadLots(ctx, query, nodes,
			func(n *Transaction) { n.Edges.Lots = []*Lot{} },
			func(n *Transaction, e *Lot) { n.Edges.Lots = append(n.Edges.Lots, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedTransactionEntries {
		if err := _q.loadTransactionEntries(ctx, query, nodes,
			func(n *Transaction) { n.appendNamedTransactionEntries(name) },
			func(n *Transaction, e *TransactionEntry) { n.appendNamedTransactionEntries(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedLots {
		if err := _q.loadLots(ctx, query, nodes,
			func(n *Transaction) { n.appendNamedLots(name) },
			func(n *Transaction, e *Lot) { n.appendNamedLots(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TransactionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Transaction, init func(*Transaction), assign func(*Transaction, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Transaction)
	for i := range nodes {
		if nodes[i].user_transactions == nil {
			continue
		}
		fk := *nodes[i].user_transactions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_transactions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TransactionQuery) loadHousehold(ctx context.Context, query *HouseholdQuery, nodes []*Transaction, init func(*Transaction), assign func(*Transaction, *Household)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Transaction)
	for i := range nodes {
		fk := nodes[i].HouseholdID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(household.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "household_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TransactionQuery) loadCategory(ctx context.Context, query *TransactionCategoryQuery, nodes []*Transaction, init func(*Transaction), assign func(*Transaction, *TransactionCategory)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Transaction)
	for i := range nodes {
		if nodes[i].transaction_category_transactions == nil {
			continue
		}
		fk := *nodes[i].transaction_category_transactions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(transactioncategory.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "transaction_category_transactions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TransactionQuery) loadTransactionEntries(ctx context.Context, query *TransactionEntryQuery, nodes []*Transaction, init func(*Transaction), assign func(*Transaction, *TransactionEntry)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Transaction)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.TransactionEntry(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(transaction.TransactionEntriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.transaction_transaction_entries
		if fk == nil {
			return fmt.Errorf(`foreign-key "transaction_transaction_entries" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "transaction_transaction_entries" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TransactionQuery) loadLots(ctx context.Context, query *LotQuery, nodes []*Transaction, init func(*Transaction), assign func(*Transaction, *Lot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Transaction)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Lot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(transaction.LotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.transaction_lots
		if fk == nil {
			return fmt.Errorf(`foreign-key "transaction_lots" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "transaction_lots" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TransactionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TransactionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for i := range fields {
			if fields[i] != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withHousehold != nil {
			_spec.Node.AddColumnOnce(transaction.FieldHouseholdID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TransactionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(transaction.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = transaction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *TransactionQuery) Modify(modifiers ...func(s *sql.Selector)) *TransactionSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedTransactionEntries tells the query-builder to eager-load the nodes that are connected to the "transaction_entries"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionQuery) WithNamedTransactionEntries(name string, opts ...func(*TransactionEntryQuery)) *TransactionQuery {
	query := (&TransactionEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedTransactionEntries == nil {
		_q.withNamedTransactionEntries = make(map[string]*TransactionEntryQuery)
	}
	_q.withNamedTransactionEntries[name] = query
	return _q
}

// WithNamedLots tells the query-builder to eager-load the nodes that are connected to the "lots"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionQuery) WithNamedLots(name string, opts ...func(*LotQuery)) *TransactionQuery {
	query := (&LotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedLots == nil {
		_q.withNamedLots = make(map[string]*LotQuery)
	}
	_q.withNamedLots[name] = query
	return _q
}

// TransactionGroupBy is the group-by builder for Transaction entities.
type TransactionGroupBy struct {
	selector
	build *TransactionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TransactionGroupBy) Aggregate(fns ...AggregateFunc) *TransactionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TransactionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransactionQuery, *TransactionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TransactionGroupBy) sqlScan(ctx context.Context, root *TransactionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TransactionSelect is the builder for selecting fields of Transaction entities.
type TransactionSelect struct {
	*TransactionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TransactionSelect) Aggregate(fns ...AggregateFunc) *TransactionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TransactionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransactionQuery, *TransactionSelect](ctx, _s.TransactionQuery, _s, _s.inters, v)
}

func (_s *TransactionSelect) sqlScan(ctx context.Context, root *TransactionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *TransactionSelect) Modify(modifiers ...func(s *sql.Selector)) *TransactionSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
