// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"fijoy.app/ent/transaction"
	"fijoy.app/ent/transactioncategory"
)

// TransactionCategoryCreate is the builder for creating a TransactionCategory entity.
type TransactionCategoryCreate struct {
	config
	mutation *TransactionCategoryMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *TransactionCategoryCreate) SetCreateTime(v time.Time) *TransactionCategoryCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TransactionCategoryCreate) SetNillableCreateTime(v *time.Time) *TransactionCategoryCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TransactionCategoryCreate) SetUpdateTime(v time.Time) *TransactionCategoryCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TransactionCategoryCreate) SetNillableUpdateTime(v *time.Time) *TransactionCategoryCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TransactionCategoryCreate) SetName(v string) *TransactionCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *TransactionCategoryCreate) SetType(v transactioncategory.Type) *TransactionCategoryCreate {
	_c.mutation.SetType(v)
	return _c
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_c *TransactionCategoryCreate) AddTransactionIDs(ids ...int) *TransactionCategoryCreate {
	_c.mutation.AddTransactionIDs(ids...)
	return _c
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_c *TransactionCategoryCreate) AddTransactions(v ...*Transaction) *TransactionCategoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTransactionIDs(ids...)
}

// Mutation returns the TransactionCategoryMutation object of the builder.
func (_c *TransactionCategoryCreate) Mutation() *TransactionCategoryMutation {
	return _c.mutation
}

// Save creates the TransactionCategory in the database.
func (_c *TransactionCategoryCreate) Save(ctx context.Context) (*TransactionCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransactionCategoryCreate) SaveX(ctx context.Context) *TransactionCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransactionCategoryCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := transactioncategory.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := transactioncategory.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransactionCategoryCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "TransactionCategory.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "TransactionCategory.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TransactionCategory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := transactioncategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TransactionCategory.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "TransactionCategory.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := transactioncategory.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TransactionCategory.type": %w`, err)}
		}
	}
	return nil
}

func (_c *TransactionCategoryCreate) sqlSave(ctx context.Context) (*TransactionCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransactionCategoryCreate) createSpec() (*TransactionCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &TransactionCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transactioncategory.Table, sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(transactioncategory.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(transactioncategory.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(transactioncategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(transactioncategory.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if nodes := _c.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transactioncategory.TransactionsTable,
			Columns: []string{transactioncategory.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TransactionCategoryCreateBulk is the builder for creating many TransactionCategory entities in bulk.
type TransactionCategoryCreateBulk struct {
	config
	err      error
	builders []*TransactionCategoryCreate
}

// Save creates the TransactionCategory entities in the database.
func (_c *TransactionCategoryCreateBulk) Save(ctx context.Context) ([]*TransactionCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransactionCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransactionCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransactionCategoryCreateBulk) SaveX(ctx context.Context) []*TransactionCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
