// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"beavermoney.app/ent/household"
	"beavermoney.app/ent/predicate"
	"beavermoney.app/ent/transaction"
	"beavermoney.app/ent/transactioncategory"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransactionCategoryQuery is the builder for querying TransactionCategory entities.
type TransactionCategoryQuery struct {
	config
	ctx                   *QueryContext
	order                 []transactioncategory.OrderOption
	inters                []Interceptor
	predicates            []predicate.TransactionCategory
	withHousehold         *HouseholdQuery
	withTransactions      *TransactionQuery
	loadTotal             []func(context.Context, []*TransactionCategory) error
	modifiers             []func(*sql.Selector)
	withNamedTransactions map[string]*TransactionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TransactionCategoryQuery builder.
func (_q *TransactionCategoryQuery) Where(ps ...predicate.TransactionCategory) *TransactionCategoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TransactionCategoryQuery) Limit(limit int) *TransactionCategoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TransactionCategoryQuery) Offset(offset int) *TransactionCategoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TransactionCategoryQuery) Unique(unique bool) *TransactionCategoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TransactionCategoryQuery) Order(o ...transactioncategory.OrderOption) *TransactionCategoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryHousehold chains the current query on the "household" edge.
func (_q *TransactionCategoryQuery) QueryHousehold() *HouseholdQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transactioncategory.Table, transactioncategory.FieldID, selector),
			sqlgraph.To(household.Table, household.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, transactioncategory.HouseholdTable, transactioncategory.HouseholdColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTransactions chains the current query on the "transactions" edge.
func (_q *TransactionCategoryQuery) QueryTransactions() *TransactionQuery {
	query := (&TransactionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transactioncategory.Table, transactioncategory.FieldID, selector),
			sqlgraph.To(transaction.Table, transaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, transactioncategory.TransactionsTable, transactioncategory.TransactionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TransactionCategory entity from the query.
// Returns a *NotFoundError when no TransactionCategory was found.
func (_q *TransactionCategoryQuery) First(ctx context.Context) (*TransactionCategory, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{transactioncategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TransactionCategoryQuery) FirstX(ctx context.Context) *TransactionCategory {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TransactionCategory ID from the query.
// Returns a *NotFoundError when no TransactionCategory ID was found.
func (_q *TransactionCategoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{transactioncategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TransactionCategoryQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TransactionCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TransactionCategory entity is found.
// Returns a *NotFoundError when no TransactionCategory entities are found.
func (_q *TransactionCategoryQuery) Only(ctx context.Context) (*TransactionCategory, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{transactioncategory.Label}
	default:
		return nil, &NotSingularError{transactioncategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TransactionCategoryQuery) OnlyX(ctx context.Context) *TransactionCategory {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TransactionCategory ID in the query.
// Returns a *NotSingularError when more than one TransactionCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TransactionCategoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{transactioncategory.Label}
	default:
		err = &NotSingularError{transactioncategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TransactionCategoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TransactionCategories.
func (_q *TransactionCategoryQuery) All(ctx context.Context) ([]*TransactionCategory, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TransactionCategory, *TransactionCategoryQuery]()
	return withInterceptors[[]*TransactionCategory](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TransactionCategoryQuery) AllX(ctx context.Context) []*TransactionCategory {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TransactionCategory IDs.
func (_q *TransactionCategoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(transactioncategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TransactionCategoryQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TransactionCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TransactionCategoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TransactionCategoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TransactionCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TransactionCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TransactionCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TransactionCategoryQuery) Clone() *TransactionCategoryQuery {
	if _q == nil {
		return nil
	}
	return &TransactionCategoryQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]transactioncategory.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.TransactionCategory{}, _q.predicates...),
		withHousehold:    _q.withHousehold.Clone(),
		withTransactions: _q.withTransactions.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithHousehold tells the query-builder to eager-load the nodes that are connected to
// the "household" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionCategoryQuery) WithHousehold(opts ...func(*HouseholdQuery)) *TransactionCategoryQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHousehold = query
	return _q
}

// WithTransactions tells the query-builder to eager-load the nodes that are connected to
// the "transactions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionCategoryQuery) WithTransactions(opts ...func(*TransactionQuery)) *TransactionCategoryQuery {
	query := (&TransactionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTransactions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TransactionCategory.Query().
//		GroupBy(transactioncategory.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TransactionCategoryQuery) GroupBy(field string, fields ...string) *TransactionCategoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TransactionCategoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = transactioncategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TransactionCategory.Query().
//		Select(transactioncategory.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *TransactionCategoryQuery) Select(fields ...string) *TransactionCategorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TransactionCategorySelect{TransactionCategoryQuery: _q}
	sbuild.label = transactioncategory.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TransactionCategorySelect configured with the given aggregations.
func (_q *TransactionCategoryQuery) Aggregate(fns ...AggregateFunc) *TransactionCategorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TransactionCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !transactioncategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if transactioncategory.Policy == nil {
		return errors.New("ent: uninitialized transactioncategory.Policy (forgotten import ent/runtime?)")
	}
	if err := transactioncategory.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *TransactionCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TransactionCategory, error) {
	var (
		nodes       = []*TransactionCategory{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withHousehold != nil,
			_q.withTransactions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TransactionCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TransactionCategory{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withHousehold; query != nil {
		if err := _q.loadHousehold(ctx, query, nodes, nil,
			func(n *TransactionCategory, e *Household) { n.Edges.Household = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTransactions; query != nil {
		if err := _q.loadTransactions(ctx, query, nodes,
			func(n *TransactionCategory) { n.Edges.Transactions = []*Transaction{} },
			func(n *TransactionCategory, e *Transaction) { n.Edges.Transactions = append(n.Edges.Transactions, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedTransactions {
		if err := _q.loadTransactions(ctx, query, nodes,
			func(n *TransactionCategory) { n.appendNamedTransactions(name) },
			func(n *TransactionCategory, e *Transaction) { n.appendNamedTransactions(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TransactionCategoryQuery) loadHousehold(ctx context.Context, query *HouseholdQuery, nodes []*TransactionCategory, init func(*TransactionCategory), assign func(*TransactionCategory, *Household)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TransactionCategory)
	for i := range nodes {
		fk := nodes[i].HouseholdID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(household.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "household_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TransactionCategoryQuery) loadTransactions(ctx context.Context, query *TransactionQuery, nodes []*TransactionCategory, init func(*TransactionCategory), assign func(*TransactionCategory, *Transaction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*TransactionCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(transaction.FieldCategoryID)
	}
	query.Where(predicate.Transaction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(transactioncategory.TransactionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CategoryID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "category_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TransactionCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TransactionCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(transactioncategory.Table, transactioncategory.Columns, sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transactioncategory.FieldID)
		for i := range fields {
			if fields[i] != transactioncategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withHousehold != nil {
			_spec.Node.AddColumnOnce(transactioncategory.FieldHouseholdID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TransactionCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(transactioncategory.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = transactioncategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *TransactionCategoryQuery) Modify(modifiers ...func(s *sql.Selector)) *TransactionCategorySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedTransactions tells the query-builder to eager-load the nodes that are connected to the "transactions"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *TransactionCategoryQuery) WithNamedTransactions(name string, opts ...func(*TransactionQuery)) *TransactionCategoryQuery {
	query := (&TransactionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedTransactions == nil {
		_q.withNamedTransactions = make(map[string]*TransactionQuery)
	}
	_q.withNamedTransactions[name] = query
	return _q
}

// TransactionCategoryGroupBy is the group-by builder for TransactionCategory entities.
type TransactionCategoryGroupBy struct {
	selector
	build *TransactionCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TransactionCategoryGroupBy) Aggregate(fns ...AggregateFunc) *TransactionCategoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TransactionCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransactionCategoryQuery, *TransactionCategoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TransactionCategoryGroupBy) sqlScan(ctx context.Context, root *TransactionCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TransactionCategorySelect is the builder for selecting fields of TransactionCategory entities.
type TransactionCategorySelect struct {
	*TransactionCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TransactionCategorySelect) Aggregate(fns ...AggregateFunc) *TransactionCategorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TransactionCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransactionCategoryQuery, *TransactionCategorySelect](ctx, _s.TransactionCategoryQuery, _s, _s.inters, v)
}

func (_s *TransactionCategorySelect) sqlScan(ctx context.Context, root *TransactionCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *TransactionCategorySelect) Modify(modifiers ...func(s *sql.Selector)) *TransactionCategorySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
