// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"fijoy.app/ent/household"
	"fijoy.app/ent/transaction"
	"fijoy.app/ent/transactioncategory"
)

// TransactionCategoryCreate is the builder for creating a TransactionCategory entity.
type TransactionCategoryCreate struct {
	config
	mutation *TransactionCategoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *TransactionCategoryCreate) SetCreateTime(v time.Time) *TransactionCategoryCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TransactionCategoryCreate) SetNillableCreateTime(v *time.Time) *TransactionCategoryCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TransactionCategoryCreate) SetUpdateTime(v time.Time) *TransactionCategoryCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TransactionCategoryCreate) SetNillableUpdateTime(v *time.Time) *TransactionCategoryCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetHouseholdID sets the "household_id" field.
func (_c *TransactionCategoryCreate) SetHouseholdID(v int) *TransactionCategoryCreate {
	_c.mutation.SetHouseholdID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TransactionCategoryCreate) SetName(v string) *TransactionCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *TransactionCategoryCreate) SetType(v transactioncategory.Type) *TransactionCategoryCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetHousehold sets the "household" edge to the Household entity.
func (_c *TransactionCategoryCreate) SetHousehold(v *Household) *TransactionCategoryCreate {
	return _c.SetHouseholdID(v.ID)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_c *TransactionCategoryCreate) AddTransactionIDs(ids ...int) *TransactionCategoryCreate {
	_c.mutation.AddTransactionIDs(ids...)
	return _c
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_c *TransactionCategoryCreate) AddTransactions(v ...*Transaction) *TransactionCategoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTransactionIDs(ids...)
}

// Mutation returns the TransactionCategoryMutation object of the builder.
func (_c *TransactionCategoryCreate) Mutation() *TransactionCategoryMutation {
	return _c.mutation
}

// Save creates the TransactionCategory in the database.
func (_c *TransactionCategoryCreate) Save(ctx context.Context) (*TransactionCategory, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransactionCategoryCreate) SaveX(ctx context.Context) *TransactionCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransactionCategoryCreate) defaults() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		if transactioncategory.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized transactioncategory.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := transactioncategory.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		if transactioncategory.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized transactioncategory.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := transactioncategory.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransactionCategoryCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "TransactionCategory.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "TransactionCategory.update_time"`)}
	}
	if _, ok := _c.mutation.HouseholdID(); !ok {
		return &ValidationError{Name: "household_id", err: errors.New(`ent: missing required field "TransactionCategory.household_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TransactionCategory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := transactioncategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TransactionCategory.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "TransactionCategory.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := transactioncategory.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TransactionCategory.type": %w`, err)}
		}
	}
	if len(_c.mutation.HouseholdIDs()) == 0 {
		return &ValidationError{Name: "household", err: errors.New(`ent: missing required edge "TransactionCategory.household"`)}
	}
	return nil
}

func (_c *TransactionCategoryCreate) sqlSave(ctx context.Context) (*TransactionCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransactionCategoryCreate) createSpec() (*TransactionCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &TransactionCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transactioncategory.Table, sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(transactioncategory.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(transactioncategory.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(transactioncategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(transactioncategory.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if nodes := _c.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactioncategory.HouseholdTable,
			Columns: []string{transactioncategory.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HouseholdID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transactioncategory.TransactionsTable,
			Columns: []string{transactioncategory.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TransactionCategory.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransactionCategoryUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *TransactionCategoryCreate) OnConflict(opts ...sql.ConflictOption) *TransactionCategoryUpsertOne {
	_c.conflict = opts
	return &TransactionCategoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TransactionCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TransactionCategoryCreate) OnConflictColumns(columns ...string) *TransactionCategoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TransactionCategoryUpsertOne{
		create: _c,
	}
}

type (
	// TransactionCategoryUpsertOne is the builder for "upsert"-ing
	//  one TransactionCategory node.
	TransactionCategoryUpsertOne struct {
		create *TransactionCategoryCreate
	}

	// TransactionCategoryUpsert is the "OnConflict" setter.
	TransactionCategoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *TransactionCategoryUpsert) SetUpdateTime(v time.Time) *TransactionCategoryUpsert {
	u.Set(transactioncategory.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TransactionCategoryUpsert) UpdateUpdateTime() *TransactionCategoryUpsert {
	u.SetExcluded(transactioncategory.FieldUpdateTime)
	return u
}

// SetName sets the "name" field.
func (u *TransactionCategoryUpsert) SetName(v string) *TransactionCategoryUpsert {
	u.Set(transactioncategory.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TransactionCategoryUpsert) UpdateName() *TransactionCategoryUpsert {
	u.SetExcluded(transactioncategory.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *TransactionCategoryUpsert) SetType(v transactioncategory.Type) *TransactionCategoryUpsert {
	u.Set(transactioncategory.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TransactionCategoryUpsert) UpdateType() *TransactionCategoryUpsert {
	u.SetExcluded(transactioncategory.FieldType)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TransactionCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TransactionCategoryUpsertOne) UpdateNewValues() *TransactionCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(transactioncategory.FieldCreateTime)
		}
		if _, exists := u.create.mutation.HouseholdID(); exists {
			s.SetIgnore(transactioncategory.FieldHouseholdID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TransactionCategory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TransactionCategoryUpsertOne) Ignore() *TransactionCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransactionCategoryUpsertOne) DoNothing() *TransactionCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransactionCategoryCreate.OnConflict
// documentation for more info.
func (u *TransactionCategoryUpsertOne) Update(set func(*TransactionCategoryUpsert)) *TransactionCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransactionCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TransactionCategoryUpsertOne) SetUpdateTime(v time.Time) *TransactionCategoryUpsertOne {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TransactionCategoryUpsertOne) UpdateUpdateTime() *TransactionCategoryUpsertOne {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetName sets the "name" field.
func (u *TransactionCategoryUpsertOne) SetName(v string) *TransactionCategoryUpsertOne {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TransactionCategoryUpsertOne) UpdateName() *TransactionCategoryUpsertOne {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *TransactionCategoryUpsertOne) SetType(v transactioncategory.Type) *TransactionCategoryUpsertOne {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TransactionCategoryUpsertOne) UpdateType() *TransactionCategoryUpsertOne {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *TransactionCategoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransactionCategoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransactionCategoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TransactionCategoryUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TransactionCategoryUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TransactionCategoryCreateBulk is the builder for creating many TransactionCategory entities in bulk.
type TransactionCategoryCreateBulk struct {
	config
	err      error
	builders []*TransactionCategoryCreate
	conflict []sql.ConflictOption
}

// Save creates the TransactionCategory entities in the database.
func (_c *TransactionCategoryCreateBulk) Save(ctx context.Context) ([]*TransactionCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransactionCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransactionCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransactionCategoryCreateBulk) SaveX(ctx context.Context) []*TransactionCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TransactionCategory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransactionCategoryUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *TransactionCategoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *TransactionCategoryUpsertBulk {
	_c.conflict = opts
	return &TransactionCategoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TransactionCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TransactionCategoryCreateBulk) OnConflictColumns(columns ...string) *TransactionCategoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TransactionCategoryUpsertBulk{
		create: _c,
	}
}

// TransactionCategoryUpsertBulk is the builder for "upsert"-ing
// a bulk of TransactionCategory nodes.
type TransactionCategoryUpsertBulk struct {
	create *TransactionCategoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TransactionCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TransactionCategoryUpsertBulk) UpdateNewValues() *TransactionCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(transactioncategory.FieldCreateTime)
			}
			if _, exists := b.mutation.HouseholdID(); exists {
				s.SetIgnore(transactioncategory.FieldHouseholdID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TransactionCategory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TransactionCategoryUpsertBulk) Ignore() *TransactionCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransactionCategoryUpsertBulk) DoNothing() *TransactionCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransactionCategoryCreateBulk.OnConflict
// documentation for more info.
func (u *TransactionCategoryUpsertBulk) Update(set func(*TransactionCategoryUpsert)) *TransactionCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransactionCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TransactionCategoryUpsertBulk) SetUpdateTime(v time.Time) *TransactionCategoryUpsertBulk {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TransactionCategoryUpsertBulk) UpdateUpdateTime() *TransactionCategoryUpsertBulk {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetName sets the "name" field.
func (u *TransactionCategoryUpsertBulk) SetName(v string) *TransactionCategoryUpsertBulk {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TransactionCategoryUpsertBulk) UpdateName() *TransactionCategoryUpsertBulk {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *TransactionCategoryUpsertBulk) SetType(v transactioncategory.Type) *TransactionCategoryUpsertBulk {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TransactionCategoryUpsertBulk) UpdateType() *TransactionCategoryUpsertBulk {
	return u.Update(func(s *TransactionCategoryUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *TransactionCategoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TransactionCategoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransactionCategoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransactionCategoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
