// Code generated by ent, DO NOT EDIT.

package userhousehold

import (
	"time"

	"beavermoney.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldUpdateTime, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldUserID, v))
}

// HouseholdID applies equality check predicate on the "household_id" field. It's identical to HouseholdIDEQ.
func HouseholdID(v int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldHouseholdID, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldLTE(FieldUpdateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNotIn(FieldUserID, vs...))
}

// HouseholdIDEQ applies the EQ predicate on the "household_id" field.
func HouseholdIDEQ(v int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldHouseholdID, v))
}

// HouseholdIDNEQ applies the NEQ predicate on the "household_id" field.
func HouseholdIDNEQ(v int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNEQ(FieldHouseholdID, v))
}

// HouseholdIDIn applies the In predicate on the "household_id" field.
func HouseholdIDIn(vs ...int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldIn(FieldHouseholdID, vs...))
}

// HouseholdIDNotIn applies the NotIn predicate on the "household_id" field.
func HouseholdIDNotIn(vs ...int) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNotIn(FieldHouseholdID, vs...))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.UserHousehold {
	return predicate.UserHousehold(sql.FieldNotIn(FieldRole, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserHousehold {
	return predicate.UserHousehold(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserHousehold {
	return predicate.UserHousehold(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHousehold applies the HasEdge predicate on the "household" edge.
func HasHousehold() predicate.UserHousehold {
	return predicate.UserHousehold(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, HouseholdTable, HouseholdColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHouseholdWith applies the HasEdge predicate on the "household" edge with a given conditions (other predicates).
func HasHouseholdWith(preds ...predicate.Household) predicate.UserHousehold {
	return predicate.UserHousehold(func(s *sql.Selector) {
		step := newHouseholdStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserHousehold) predicate.UserHousehold {
	return predicate.UserHousehold(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserHousehold) predicate.UserHousehold {
	return predicate.UserHousehold(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserHousehold) predicate.UserHousehold {
	return predicate.UserHousehold(sql.NotPredicates(p))
}
