name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  web-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Vitest
        working-directory: "./apps/web"
        run: pnpm test

  server-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - run: go version

      - name: Go Testing
        working-directory: "./apps/server"
        run: go test ./...
